<?php
/**
 * Форма публикации персонального статуса
 */
$this->form->setAttribute('action', $this->url($this->getRoute()->route['controller'], 
    ['action' => 'personal']
    )
);
echo $this->form()->openTag($this->form);
echo '<fieldset data-role="fieldcontain">';
    echo $this->formRow($this->form->get('personal')->setValue($this->escapeHTML($add->personal)), null, false).PHP_EOL;
echo '</fieldset>';
echo '<fieldset data-role="controlgroup" data-type="horizontal">';
    echo $this->formRow($this->form->get('share'), null, false).PHP_EOL;
    echo $this->formRow($this->form->get('submit'), null, false).PHP_EOL;
echo '</fieldset>';
echo $this->form()->closeTag();

?>  
<script language="javascript" type="text/javascript">  
$(document).ready(function(){
	//create a new WebSocket object.
	var wsUri = "ws://zf.local:9000/websocket"; 	
	websocket = new WebSocket(wsUri); 
	
	websocket.onopen = function(ev) { // connection is open 
		console.log("Connected!"); //notify user
	}

	$('#send-btn').click(function(){ //use clicks message send button	
		var mymessage = $('#message').val(); //get message text
		var myname = $('#name').val(); //get user name
		
		if(myname == ""){ //empty name?
			alert("Enter your Name please!");
			return;
		}
		if(mymessage == ""){ //emtpy message?
			alert("Enter Some message Please!");
			return;
		}
		
		//prepare json data
		var msg = {
		message: mymessage,
		name: myname,
		};
		//convert and send data to server
		websocket.send(JSON.stringify(msg));
	});
	
	//#### Message received from server?
	websocket.onmessage = function(ev) {
		var msg = JSON.parse(ev.data); //PHP sends Json data
		var type = msg.type; //message type
		var umsg = msg.message; //message text
		var uname = msg.name; //user name
		var ucolor = msg.color; //color

		if(type == 'usermsg') 
		{
			$('#message_box').append("<div><span class=\"user_name\" style=\"color:#"+ucolor+"\">"+uname+"</span> : <span class=\"user_message\">"+umsg+"</span></div>");
		}
		if(type == 'system')
		{
			$('#message_box').append("<div class=\"system_msg\">"+umsg+"</div>");
		}
		
		$('#message').val(''); //reset text
	};
	
	websocket.onerror	= function(ev){console.log("Error Occurred -"+ev.data);}; 
	websocket.onclose 	= function(ev){		console.log("Connection closed"); }; 
});
</script>
