<?php
/**
 * Перевод сообщений об ошибках
 * Language: Русский язык
 * Domain: success
 * Author: Stanislav WEB
 */

return [
    '(GMT - 1:00) Azores, islands of Cape Verde' => '(GMT - 1:00) Азорские острова, острова Кабо-Верде',
    '(GMT - 2:00) Mid-Atlantic time' => '(GMT - 2:00) Среднеатлантическое время',
    '(GMT - 3:00) Brazil, Buenos Aires, Georgetown, Greenland' => '(GMT - 3:00) Бразилия, Буэнос-Айрес, Джорджтаун, Гренландия',
    '(GMT - 3:30) Newfoundland' => '(GMT - 3:30) Ньюфаундленд',
    '(GMT - 4:00) Atlantic Time (Canada), Caracas, La Paz, Santiago' => '(GMT - 4:00) Атлантическое время (Канада), Каракас, Ла-Пас, Сантьяго',
    '(GMT - 5:00) Eastern Time (U.S. & Canada), Bogota, Lima, Quito' => '(GMT - 5:00) Восточное время (США и Канада), Богота, Лима, Кито',
    '(GMT - 6:00) Central Time (U.S. & Canada), Mexico' => '(GMT - 6:00) Центральное время (США и Канада), Мексика',
    '(GMT - 7:00) Mountain Time (U.S. and Canada), Arizona' => '(GMT - 7:00) Горное время (США и Канада), Аризона',
    '(GMT - 8:00) Pacific Time (U.S. & Canada), Tijuana' => '(GMT - 8:00) Тихоокеанское время (США и Канада), Тихуана',
    '(GMT - 9:00) Alaska' => '(GMT - 9:00) Аляска',
    '(GMT - 10:00) Hawaii' => '(GMT - 10:00) Гавайи',
    '(GMT - 11:00) o.Miduey, Samoa' => '(GMT - 11:00) о.Мидуэй, Самоа',
    '(GMT - 12:00) Enevetok, Kwajalein' => '(GMT - 12:00) Эневеток, Кваджалейн',
    '(GMT) Casablanca, Dublin, Edinburgh, Lisbon, London, Monrovia' => '(GMT) Касабланка, Дублин, Эдинбург, Лиссабон, Лондон, Монровия',
    '(GMT + 1:00) Amsterdam, Berlin, Brussels, Madrid, Paris, Rome' => '(GMT + 1:00) Амстердам, Берлин, Брюссель, Мадрид, Париж, Рим',
    '(GMT + 2:00) Cairo, Helsinki, Kaliningrad, South Africa, Warsaw, Kyiv' => '(GMT + 2:00) Каир, Хельсинки, Калининград, Южная Африка, Варшава, Киев',
    '(GMT + 3:00) Baghdad, Riyadh, Moscow, Nairobi' => '(GMT + 3:00) Багдад, Эр-Рияд, Москва, Найроби',
    '(GMT + 3:30) Tehran' => '(GMT + 3:30) Тегеран',
    '(GMT + 4:00) Abu Dhabi, Baku, Muscat, Tbilisi' => '(GMT + 3:30) Абу-Даби, Баку, Мускат, Тбилиси',
    '(GMT + 4:30) Kabul' => '(GMT + 4:30) Кабул',
    '(GMT + 5:00) Ekaterinburg, Islamabad, Karachi, Tashkent' => '(GMT + 5:00) Екатеринбург, Исламабад, Карачи, Ташкент',
    '(GMT + 5:30) Bombay, Calcutta, Madras, New Delhi' => '(GMT + 5:30) Бомбей, Калькутта, Мадрас, Нью-Дели',
    '(GMT + 6:00) Alma-Ata, Colombo, Dhaka, Novosibirsk, Omsk' => '(GMT + 6:00) Алма-Ата, Коломбо, Дхака, Новосибирск, Омск',
    '(GMT + 7:00) Bangkok, Hanoi, Jakarta, Krasnoyarsk' => '(GMT + 7:00) Бангкок, Ханой, Джакарта, Красноярск',
    '(GMT + 8:00) Beijing, Hong Kong, Perth, Singapore, Taipei' => '(GMT + 8:00) Пекин, Гонконг, Перт, Сингапур, Тайпей',
    '(GMT + 9:00) Osaka, Sapporo, Seoul, Tokyo, Yakutsk' => '(GMT + 9:00) Осака, Саппоро, Сеул, Токио, Якутск',
    '(GMT + 9:30) Adelaide, Darwin' => '(GMT + 9:30) Аделаида, Дарвин',
    '(GMT + 10:00) Canberra, Melbourne, Guam, Sydney, Vladivostok' => '(GMT + 10:00) Канберра, Мельбурн, Гуам, Сидней, Владивосток',
    '(GMT + 11:00) Magadan, New Caledonia, Solomon Islands' => '(GMT + 11:00) Магадан, Новая Каледония, Соломоновы о-ва',
    '(GMT + 12:00) Auckland, Fiji, Kamchatka, Wellington' => '(GMT + 12:00) Окленд, Фиджи, Камчатка, Веллингтон',
    '(GMT + 13:00) Kamchatka' => '(GMT + 13:00) Камчатка',
    '(GMT + 14:00) Kiritimati (Christmas Island)' => '(GMT + 14:00) Киритимати (остров Рождества)',
];
