<?php
/**
 * Перевод сообщений об ошибках
 * Language: Українська мова
 * Domain: success
 * Author: Stanislav WEB
 */

return [
    '(GMT - 1:00) Azores, islands of Cape Verde' => '(GMT - 1:00) Азорські острови, острови Кабо-Верде',
    '(GMT - 2:00) Mid-Atlantic time' => '(GMT - 2:00) Середньоатлантичний час',
    '(GMT - 3:00) Brazil, Buenos Aires, Georgetown, Greenland' => '(GMT - 3:00) Бразилія, Буенос-Айрес, Джорджтаун, Гренландія',
    '(GMT - 3:30) Newfoundland' => '(GMT - 3:30) Ньюфаундленд',
    '(GMT - 4:00) Atlantic Time (Canada), Caracas, La Paz, Santiago' => '(GMT - 4:00) Атлантичний час (Канада), Каракас, Ла-Пас, Сантьяго',
    '(GMT - 5:00) Eastern Time (U.S. & Canada), Bogota, Lima, Quito' => '(GMT - 5:00) Східний час (США і Канада), Богота, Ліма, Кіто',
    '(GMT - 6:00) Central Time (U.S. & Canada), Mexico' => '(GMT - 6:00) Центральний час (США і Канада), Мексика',
    '(GMT - 7:00) Mountain Time (U.S. and Canada), Arizona' => '(GMT - 7:00) Гірський час (США і Канада), Арізона',
    '(GMT - 8:00) Pacific Time (U.S. & Canada), Tijuana' => '(GMT - 8:00) Тихоокеанський час (США і Канада), Тіхуана',
    '(GMT - 9:00) Alaska' => '(GMT - 9:00) Аляска',
    '(GMT - 10:00) Hawaii' => '(GMT - 10:00) Гаваї',
    '(GMT - 11:00) o.Miduey, Samoa' => '(GMT - 11:00) о.Мидвей, Самоа',
    '(GMT - 12:00) Enevetok, Kwajalein' => '(GMT - 12:00) Еневеток, Кваджалейн',
    '(GMT) Casablanca, Dublin, Edinburgh, Lisbon, London, Monrovia' => '(GMT) Касабланка, Дублін, Единбург, Лісабон, Лондон, Монровія',
    '(GMT + 1:00) Amsterdam, Berlin, Brussels, Madrid, Paris, Rome' => '(GMT + 1:00) Амстердам, Берлін, Брюссель, Мадрид, Париж, Рим',
    '(GMT + 2:00) Cairo, Helsinki, Kaliningrad, South Africa, Warsaw, Kyiv' => '(GMT + 2:00) Каїр, Гельсінкі, Калінінград, Південна Африка, Варшава, Київ',
    '(GMT + 3:00) Baghdad, Riyadh, Moscow, Nairobi' => '(GMT + 3:00) Багдад, Ер-Ріяд, Москва, Найробі',
    '(GMT + 3:30) Tehran' => '(GMT + 3:30) Тегеран',
    '(GMT + 4:00) Abu Dhabi, Baku, Muscat, Tbilisi' => '(GMT + 3:30) Абу-Дабі, Баку, Мускат, Тбілісі',
    '(GMT + 4:30) Kabul' => '(GMT + 4:30) Кабул',
    '(GMT + 5:00) Ekaterinburg, Islamabad, Karachi, Tashkent' => '(GMT + 5:00) Єкатеринбург, Ісламабад, Карачі, Ташкент',
    '(GMT + 5:30) Bombay, Calcutta, Madras, New Delhi' => '(GMT + 5:30) Бомбей, Калькутта, Мадрас, Нью-Делі',
    '(GMT + 6:00) Alma-Ata, Colombo, Dhaka, Novosibirsk, Omsk' => '(GMT + 6:00) Алма-Ата, Коломбо, Дакка, Новосибірськ, Омськ',
    '(GMT + 7:00) Bangkok, Hanoi, Jakarta, Krasnoyarsk' => '(GMT + 7:00) Бангкок, Ханой, Джакарта, Красноярськ',
    '(GMT + 8:00) Beijing, Hong Kong, Perth, Singapore, Taipei' => '(GMT + 8:00) Пекін, Гонконг, Перт, Сінгапур, Тайбей',
    '(GMT + 9:00) Osaka, Sapporo, Seoul, Tokyo, Yakutsk' => '(GMT + 9:00) Осака, Саппоро, Сеул, Токіо, Якутськ',
    '(GMT + 9:30) Adelaide, Darwin' => '(GMT + 9:30) Аделаїда, Дарвін',
    '(GMT + 10:00) Canberra, Melbourne, Guam, Sydney, Vladivostok' => '(GMT + 10:00) Канберра, Мельбурн, Гуам, Сідней, Владивосток',
    '(GMT + 11:00) Magadan, New Caledonia, Solomon Islands' => '(GMT + 11:00) Магадан, Нова Каледонія, Соломонові Острови',
    '(GMT + 12:00) Auckland, Fiji, Kamchatka, Wellington' => '(GMT + 12:00) Окленд, Фіджі, Камчатка, Веллінгтон',
    '(GMT + 13:00) Kamchatka' => '(GMT + 13:00) Камчатка',
    '(GMT + 14:00) Kiritimati (Christmas Island)' => '(GMT + 14:00) Кірітіматі (острів Різдва)',
];
