<?php echo $this->doctype().PHP_EOL;?>
<html lang="<?php echo $this->lang;?>">
    <head>
        <?php echo $this->headMeta()
                // META информация
                ->setCharset('UTF-8')
                //->appendHttpEquiv('Cache-Control', 'public')
                //->appendHttpEquiv('Cache-Control', 'max-age=99090600, must-revalidate')
                ->appendName('keywords', '')
                ->appendName('description', '')
                ->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1')
                ->appendName('generator', 'Zend Framework 2.1.5')
                ->appendName('author', 'Stanislav WEB');
        ?>
        <?php echo $this->headTitle()->setSeparator(' / ');?>
        <?php echo $this->headLink(array('rel'=>'shortcut icon', 'href'=>$this->basePath().'/images/favicon.ico')); ?>
        <?php echo $this->headScript(); ?>
    </head>
    <body>
        <section data-role="page" data-theme="a" id="page">
            <header data-role="header" data-theme="a" data-position="fixed" class="ui-admin-header">
                <div class="ui-grid-a">
                    <div class="ui-block-a">
                        <a href="#Language" title="<?php echo $this->translate('Choose a language', 'default');?>" class="ui-hover-btn ui-admin-nav-btn" data-role="button" data-rel="dialog"><img src="/images/flags/small/<?php echo $this->getLang('code');?>.png" alt="<?php echo $this->getLang('code');?>" /></a>
                        <a href="#" id="login" title="Администратор" class="ui-hover-btn ui-admin-nav-btn" data-role="button" data-rel="dialog"><img src="/images/admin/admin.gif" alt="Администратор" />&nbsp;&nbsp;<span><?php echo $this->user->name?></span></a>                
                    </div>
                    <div class="ui-block-b">
                        <h1 class="ui-admin-logo">
                            <a href="<?php echo $this->url('social', array('lang' => $this->getLang('code')), array('force_canonical' => true));?>"><img src="/images/mobile/logo.png" alt="Logo"></a>
                        </h1>              
                    </div>
                    <div class="ui-block-c" align="right">
                        <a href="#" class="ui-hover-btn ui-admin-nav-btn" data-role="button" onclick="return false;" id="clock" data-rel="dialog"></a>
                        <a href="<?php echo $this->url('logout');?>" title="<?php echo $this->translate('Logout', 'admin');?>" class="ui-hover-btn ui-admin-nav-btn" data-transition="pop" data-role="button"><img src="/images/admin/mini_logout.png" alt="<?php echo $this->translate('Logout', 'admin')?>" /></a>                
                    </div>
                </div>
            </header>   
            <!-- Контент -->
            <?php echo $this->content;?>
            <!-- Контент -->
            <footer data-position="fixed" data-role="footer" class="ui-bar footer" data-theme="a">
                <h4>&copy; 2013  <a href="/"><?php echo $this->translate('Social Mobile', 'default')?></a> <?php echo $this->translate('powered by', 'default')?> <?php echo Zend\Version\Version::VERSION_SERVICE_ZEND;?> <?php echo Zend\Version\Version::VERSION;?> <?php echo $this->translate('All rights reserved.', 'default')?></h4>
            </footer>
        </section>
        <?php echo $this->socialPlugin('language'); // виджет выбора языка ?>        
    </body>
</html>