<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'plugins/breadcrumbs'                      => __DIR__ . '/view/plugins/breadcrumbs.phtml',
    'plugins/language'                         => __DIR__ . '/view/plugins/language.phtml',
    'plugins/qrcode'                           => __DIR__ . '/view/plugins/qrcode.phtml',
    'plugins/header'                           => __DIR__ . '/view/plugins/header.phtml',
    'plugins/admin-pager'                      => __DIR__ . '/view/plugins/admin-pager.phtml',
    'plugins/zf_flash_wall/flashwall'          => __DIR__ . '/view/plugins/zf_flash_wall/flashwall.phtml',
    'plugins/zf_plugin_bookmarks/bookmarks'    => __DIR__ . '/view/plugins/zf_plugin_bookmarks/bookmarks.phtml',
    'plugins/zf_plugin_menu/admin-info-menu'   => __DIR__ . '/view/plugins/zf_plugin_menu/admin-info-menu.phtml',
    'plugins/zf_plugin_menu/admin-main-menu'   => __DIR__ . '/view/plugins/zf_plugin_menu/admin-main-menu.phtml',
    'plugins/zf_plugin_menu/admin-nav-menu'    => __DIR__ . '/view/plugins/zf_plugin_menu/admin-nav-menu.phtml',
    'plugins/zf_plugin_menu/admin-status-menu' => __DIR__ . '/view/plugins/zf_plugin_menu/admin-status-menu.phtml',
    'plugins/zf_plugin_menu/user-left-menu'    => __DIR__ . '/view/plugins/zf_plugin_menu/user-left-menu.phtml',
    'plugins/zf_plugin_menu/user-topnav-menu'  => __DIR__ . '/view/plugins/zf_plugin_menu/user-topnav-menu.phtml',
    'plugins/zf_plugin_notices/rules'          => __DIR__ . '/view/plugins/zf_plugin_notices/rules.phtml',
    'plugins/zf_users_profile/usersonline'     => __DIR__ . '/view/plugins/zf_users_profile/usersonline.phtml',
);
