<?php
/**
 * Перевод основного модуля
 * Language: Русский язык
 * Domain: admin (default)
 * Author: Stanislav WEB
 */

return array(
    
    // Разделы
    
    'Control Panel'         =>  'Панель управления',
    'Logout'                =>  'Выход',
    'Wellcome to Control Panel' =>  'Добро пожаловать в Панель Управления',
    'Server overview'       =>  'Серверная информация',
    'System overview'       =>  'Информация о системе',
    'Plugins control'                       =>  'Управление плагинами',
    'Plugins control ▶ %s'                  =>  'Управление плагинами ▶ %s',
    'Plugins control ▶ Register plugin'     =>  'Управление плагинами ▶ Регистрировать плагин',
    'Register plugin'                       =>  'Регистрировать плагин',
    'Users control'                         =>  'Управление пользователями',
    'Users control ▶ %s'                    =>  'Управление пользователями ▶ %s',
    'Users control ▶ Edit "%s"'             =>  'Управление пользователями ▶ Редактировать "%s"',
    
    'Submissions control'       =>  'Управление рассылкой',
    'Submissions control ▶ %s'  =>  'Управление рассылкой ▶ %s',
    
    
    
    

    
    // Элементы
    
    'All'	    =>  'Все',
    'edit'          =>  'ред.',
    'User'	    =>  'Пользователь',
    'Photo'         =>  'Фото',
    'Location'      =>  'Местоположение',
    'Information'   =>  'Дополнительная информация',
    'Login'	    =>	'Логин',
    
    'Displayed name'=>  'Отображаемое имя',
    'Phone'         =>  'Телефон',
    'Gender'        =>  'Пол',
    'male'          =>  'мужской',
    'female'        =>  'женский',
    'Height / Weight'   =>  'Рост / Вес',
    'Interests'     =>  'Интересы',
    'About'         =>  'О себе',
    'Timezone'      =>  'Часовой пояс',
    'Alias'         =>  'Короткое имя (для URL)',
    'Fill the contact email'    =>  'Заполните контактный email адрес',
    'Fill the contact phone number' =>  'Заполните контактный номер телефона',
    
    'Accesibility'  =>  'Служебная информация',
    'Personal data' =>  'Персональные данные',
    'Settings'      =>  'Настройки пользователя',
    'Password'      =>  'Пароль',
    'Login must be required'    =>  'Укажите логин!',
    'Leave this part blank if there is no need to change the password'  =>  'Оставте пустым, если нет необходимости смены',
    'Retype password'   =>  'Подтвердите пароль',
    'Country'       =>  'Страна',
    'Region'        =>  'Регион',
    'City'          =>  'Насленный пункт',
    
    
    
    
    'Group'	    =>	'Группа',
    'Edit - '       =>  'Редактировать - ',
    'Register date'	=>	'Дата регистрации',
    'Last visit date'	=>	'Последний визит',
    'What to do with markup ?'	=> 'Что делать с отмеченными?',
    
    
    'Title'                 =>  'Название',
    'Description'           =>  'Описание',
    'System'                =>  'Идентификатор в системе',
    'Type'                  =>  'Тип',
    'Status'                =>  'Статус',
    'Mode'                  =>  'Режим',
    'Save params'           =>  'Сохранить настройки',    
    
    'Edit'      =>  'Изменить',
    'On'        =>  'Вкл.',
    'Off'       =>  'Выкл.',
    'Delete'    =>  'Удалить',
    'Add this'  =>  'Добавить',
    'Do it!'    =>  'Подтведить',
    'active'    =>  'активно',
    'off'       =>  'выкл.',
    'enabled'   =>  'активен',
    'disabled'  =>  'выключен',
    'banned'    =>  'забанен',   
    'Ban'       =>  'Бан',
    'Unban'     =>  'Разбан.',
    'Enable'    =>  'Актив.',
    'Disable'   =>  'Выкл.',
    
    'Please typing login here...'   =>  'Пожалуйста введите логин...',
    'Please typing name...'         =>  'Введите имя...',
    'Select status'                 =>  'Выберите статус',
    'Select role'                   =>  'Выберите группу',
    'Sorting by...'                 =>  'Сортировать по...',
    'IDentifier'                    =>  'Идентификатор',
    'Name'                          =>  'Имя',
    'Birthday'                      =>  'День рождения',
    'Role'                          =>  'Группа',
    'Rating'                        =>  'Рейтинг',
    'Register date'                 =>  'Дата регистрации',
    'Last visit date'               =>  'Последний визит',
    'Most visited'                  =>  'Самые посещаемые',
    'Search'                        =>  'Поиск',
    'Reset'                         =>  'Сбросить',
    
);