<?php
/**
 * Перевод основного модуля
 * Language: Русский язык
 * Domain: admin (default)
 * Author: Stanislav WEB
 */

return array(
    
    // Разделы
    
    'Control Panel'         =>  'Панель управления',
    'Logout'                =>  'Выход',
    'Wellcome to Control Panel' =>  'Добро пожаловать в Панель Управления',
    'Server overview'       =>  'Серверная информация',
    'System overview'       =>  'Информация о системе',
    'Plugins control'                       =>  'Управление плагинами',
    'Plugins control ▶ %s'                  =>  'Управление плагинами ▶ %s',
    'Plugins control ▶ Register plugin'     =>  'Управление плагинами ▶ Регистрировать плагин',
  
    'Users Control'                         =>  'Управление пользователями',
    'Users Control ▶ %s'                    =>  'Управление пользователями ▶ %s',
    'Users Control ▶ Edit "%s"'             =>  'Управление пользователями ▶ Редактировать "%s"',
    
    'Submissions control'       =>  'Управление рассылкой',
    'Submissions control ▶ %s'  =>  'Управление рассылкой ▶ %s',
    
    
    
    

    
    // Элементы
    
    'All'	    =>  'Все',
    'edit'          =>  'ред.',
    'User'	    =>  'Пользователь',
    'Photo'         =>  'Фото',
    'Location'      =>  'Местоположение',
    'Information'   =>  'Дополнительная информация',
    'Login'	    =>	'Логин',
    'Group'	    =>	'Группа',
    
    'Register date'	=>	'Дата регистрации',
    'Last visit date'	=>	'Последний визит',
    'What to do with markup ?'	=> 'Что делать с отмеченными?',
    
    
    'Title'                 =>  'Название',
    'Description'           =>  'Описание',
    'System'                =>  'Идентификатор в системе',
    'Type'                  =>  'Тип',
    'Status'                =>  'Статус',
    'Mode'                  =>  'Режим',
    'Save params'           =>  'Сохранить настройки',    
    
    'Edit'      =>  'Изменить',
    'On'        =>  'Вкл.',
    'Off'       =>  'Выкл.',
    'Delete'    =>  'Удалить',
    'Add this'  =>  'Добавить',
    'Do it!'    =>  'Подтведить',
    'active'    =>  'активно',
    'off'       =>  'выкл.',
    'enabled'   =>  'активен',
    'disabled'  =>  'выключен',
    'banned'    =>  'забанен',   
    'Ban'       =>  'Бан',
    'Unban'     =>  'Разбан.',
    'Enable'    =>  'Актив.',
    'Disable'   =>  'Выкл.',
);