<?php
/**
 * Перевод основного модуля
 * Language: Русский язык
 * Domain: admin (default)
 * Author: Stanislav WEB
 */

return array(
    
    // Разделы
    
    'Control Panel'         =>  'Панель управления',
    'Logout'                =>  'Выход',
    'Wellcome to Control Panel' =>  'Добро пожаловать в Панель Управления',
    'Server overview'       =>  'Серверная информация',
    'System overview'       =>  'Информация о системе',
    'Users Control'         =>  'Управление пользователями',
    
    // Элементы
    
    'All'	    =>  'Все',
    'User'	    =>  'Пользователь',
    'Photo'         =>  'Фото',
    'Location'      =>  'Местоположение',
    'Information'   =>  'Дополнительная информация',
    'Login'	    =>	'Логин',
    'Group'	    =>	'Группа администрирования',
    'Register date'	=>	'Дата регистрации',
    'Last visit date'	=>	'Последний визит',
    'What to do with markup ?'	=> 'Что делать с отмеченными?'
);