<?php
/**
 * Перевод основного модуля
 * Language: Українська мова
 * Domain: admin (default)
 * Author: Stanislav WEB
 */

return array(
    
    // Разделы

    'Control Panel'         =>  'Панель управління',
    'Logout'                =>  'Вихід',
    'Wellcome to Control Panel' =>  'Ласкаво просимо до Панелі Управління',
    'Server overview'       =>  'Серверна інформація',
    'System overview'       =>  'Системна інформація',
    'Plugins control'                       =>  'Керування плагінами',
    'Plugins control ▶ %s'                  =>  'Керування плагінами ▶ %s',
    'Plugins control ▶ Register plugin'     =>  'Управління плагінами ▶ Реєструвати плагін',
    
    'Users Control'                         =>  'Управління користувачами',
    'Users Control ▶ %s'                    =>  'Управління користувачами ▶ %s',
    'Users Control ▶ Edit "%s"'             =>  'Управління користувачами ▶ Редагувти "%s"',    
    
    'Submissions control ▶ %s'  =>  'Керування розсилкою ▶ %s',
    'Submissions control'   =>  'Керування розсилкою',
    
    'Title'                 =>  'Назва',
    'Description'           =>  'Опис',
    'System'                =>  'Ідентифікатор в системі',
    'Type'                  =>  'Тип',
    'Status'                =>  'Статус',
    'Mode'                  =>  'Режим',
    'Save params'           =>  'Зберегти налаштування',
    
    // Элементы
    
    'All'	    =>  'Усі',
    'edit'          =>  'ред.',
    'User'	    =>  'Користувач',
    'Photo'         =>  'Фото',
    'Location'      =>  'Місцезнаходження',
    'Information'   =>  'Додаткова інформація',    
    'Login'	    =>	'Логін',
    'Group'	    =>	'Група',
    'Register date'	=>	'Дата реєстрації',
    'Last visit date'	=>	'Останній візит',    
    'What to do with markup ?'	=> 'Що робити з відмітками?',
    'Edit'      =>  'Редагувати',
    'On'        =>  'Вкл.',
    'Off'       =>  'Вимк.',
    'Delete'    =>  'Удалити',
    'Do it!'    =>  'Підтведити',    
    'Add this'  =>  'Добавити',
    'active'    =>  'активно',
    'off'       =>  'вимк.', 
    'enabled'   =>  'активний',
    'disabled'  =>  'вимкнений',
    'banned'    =>  'забанений',
    'Ban'       =>  'Бан',
    'Unban'     =>  'Разбан.',
    'Enable'    =>  'Актив.',
    'Disable'   =>  'Вимк.',
);