<?php
/**
 * Перевод основного модуля
 * Language: Українська мова
 * Domain: admin (default)
 * Author: Stanislav WEB
 */

return array(
    
    // Разделы

    'Control Panel'         =>  'Панель управління',
    'Logout'                =>  'Вихід',
    'Wellcome to Control Panel' =>  'Ласкаво просимо до Панелі Управління',
    'Server overview'       =>  'Серверна інформація',
    'System overview'       =>  'Системна інформація',
    'Users Control'         =>  'Управління користувачами',
    'Plugins control'       =>  'Управління плагінами',
    
    // Элементы
    
    'All'	    =>  'Усі',
    'User'	    =>  'Користувач',
    'Photo'         =>  'Фото',
    'Location'      =>  'Місцезнаходження',
    'Information'   =>  'Додаткова інформація',    
    'Login'	    =>	'Логін',
    'Group'	    =>	'Група админістратора',
    'Register date'	=>	'Дата реєстрації',
    'Last visit date'	=>	'Останній візит',    
    'What to do with markup ?'	=> 'Що робити з відмітками?',
);