<?php
/**
 * Перевод основного модуля
 * Language: Українська мова
 * Domain: admin (default)
 * Author: Stanislav WEB
 */

return [
    
    // Разделы

    'Control Panel'         =>  'Панель управління',
    'Logout'                =>  'Вихід',
    'Wellcome to Control Panel' =>  'Ласкаво просимо до Панелі Управління',
    'Server overview'       =>  'Серверна інформація',
    'System overview'       =>  'Системна інформація',
    'Plugins control'                       =>  'Керування плагінами',
    'Plugins control ▶ %s'                  =>  'Керування плагінами ▶ %s',
    'Plugins control ▶ Register plugin'     =>  'Управління плагінами ▶ Реєструвати плагін',
    'Register plugin'                       =>  'Реєструвати плагін',
    
    'Users control'                         =>  'Управління користувачами',
    'Users control ▶ %s'                    =>  'Управління користувачами ▶ %s',
    'Users control ▶ Edit "%s"'             =>  'Управління користувачами ▶ Редагувти "%s"',    
    
    'Submissions control ▶ %s'  =>  'Керування розсилкою ▶ %s',
    'Submissions control'   =>  'Керування розсилкою',
    
    'Title'                 =>  'Назва',
    'Description'           =>  'Опис',
    'System'                =>  'Ідентифікатор в системі',
    'Type'                  =>  'Тип',
    'Status'                =>  'Статус',
    'Mode'                  =>  'Режим',
    'Save params'           =>  'Зберегти налаштування',
    
    // Элементы
    
    'All'	    =>  'Усі',
    'edit'          =>  'ред.',
    'User'	    =>  'Користувач',
    'Photo'         =>  'Фото',
    'Location'      =>  'Місцезнаходження',
    'Information'   =>  'Додаткова інформація',    
    'Login'	    =>	'Логін',
    'Group'	    =>	'Група',
    'Edit - '       =>  'Редагувати - ',
    'Register date'	=>	'Дата реєстрації',
    'Last visit date'	=>	'Останній візит',    
    'What to do with markup ?'	=> 'Що робити з відмітками?',
    'Edit'      =>  'Редагувати',
    'On'        =>  'Вкл.',
    'Off'       =>  'Вимк.',
    'Delete'    =>  'Удалити',
    'Do it!'    =>  'Підтведити',    
    'Add this'  =>  'Добавити',
    'active'    =>  'активно',
    'off'       =>  'вимк.', 
    'enabled'   =>  'активний',
    'disabled'  =>  'вимкнений',
    'banned'    =>  'забанений',
    'Ban'       =>  'Бан',
    'Unban'     =>  'Разбан.',
    'Enable'    =>  'Актив.',
    'Disable'   =>  'Вимк.',
    'Please typing login here ...' => 'Будь ласка введіть логін ...',
    'Select status'                 =>  'Оберіть статус',
    'Select role'  =>  'Виберіть групу',
    'Sorting by...'                 =>  'Сортувати по...',
    'IDentifier'                    =>  'Iдентифікатор',
    'Name'  =>  'Iм\'я',
    'Birthday'  =>  'День народження',
    'Role'  =>  'Група',
    'Rating'  =>  'Рейтинг',
    'Register date'  =>  'Дата реєстрації',
    'Last visit date'  =>  'Останній візит',
    'Most visited'  =>  'Найбільш відвідувані',
    'Search'  =>  'Пошук',
    'Reset'  =>  'Скинути',
];