<?php
/**
 * Перевод сообщений об ошибках
 * Language: Русский язык
 * Domain: errors
 * Author: Stanislav WEB
 */

return array(
    'Action error! You can not send form without POST!' =>	'Произошла ошибка! Вы не можете отправить форму методом GET!',
    'Plugins not found'                                 =>	'Плагины не найдены',
    'Plugin not found'                                  =>      'Плагин не найден',
    'Action not selected'                               =>	'Не выбрано действие',
    'Not selected items'                                =>	'Не выбраны плагины для обработки',
    'Action is not available'                           =>      'Действие не доступно',
    'Error while deleting'                              =>      'Ошибка при удалении',
    'Error while update status'                         =>      'Ошибка при обновлении статуса',
    'This plugin is only for reading, the changes may lead to malfunction of the system'    =>      'Этот плагин только для чтения, изменения могут привести к сбою в работе системы',
    'Plugin configuration\'s has been changed'          =>      'Конфигурация плагина сохранена',
    'Plugin has been registered'                        =>      'Плагин успешно зарегистрирован',
    'An error occurred while registering plugin'        =>      'Возникла ошибка при регистрации плагина',
    'All fields must be required'                       =>      'Все поля должны быть заполнены',
    'Plugin was deleted successfuly'                    =>      'Плагин успешно удален',
);
