<?php
/**
 * Перевод сообщений об ошибках
 * Language: Українська мова
 * Domain: errors
 * Author: Stanislav WEB
 */

return array(
    'Action error! You can not send form without POST!' =>	'Помилка! Ви не зможете відправити форму GET!',
    'Plugins not found'                                 =>	'Плагіни не знайдени',
    'Plugin not found'                                  =>      'Плагін не знайден',
    'Users not found'                                   =>      'В системі немає жодного користувача',
    'User not found'                                    =>      'Не знайден користувач',
    'Action not selected'                               =>	'Оберить дію',
    'Not selected items'                                =>	'Відмідьте елементи для обробки',
    'Action is not available'                           =>      'Не зрозуміла дія',
    'Error while deleting'                              =>      'Помилка при видаленні',
    'Error while update status'                         =>      'Помилка при оновленні статусу',
    'Error while update the role'                       =>      'Помилка при оновленні ролі',
    'This plugin is only for reading, the changes may lead to malfunction of the system'    =>      'Цей плагін тільки для читання, зміни можуть привести до збою в роботі системи',
    'Plugin configuration\'s has been changed'          =>      'Конфігурація плагіна була змінена',
    'Plugin has been registered'                        =>      'Плагін успішно зареєстрован',
    'An error occurred while registering plugin'        =>      'Виникла помилка при реєстрації плагіна',    
    'All fields must be required'                       =>      'Всі поля повинні бути заповнені',
    'Item(s) was deleted successfuly'                   =>      'Записи успішно видалени',
    'Item(s) was update successfuly'                    =>      'Записи успішно обовлені',
    'Only an administrator can assign roles to users'   =>      'Тільки адміністратор може призначати ролі користувачам',
);
