<!-- Слой авторизации -->
<div id="auth" class="inner-tabs boxshadow">
    <?php
    echo $this->formElementerrors($this->authForm, array('class' => "ui-error")).PHP_EOL; // сообщение об ошибке
    ?>
    <?php if(!empty($this->errorMsgAuth)):?>
        <ul class="ui-error">
            <li>
                <?=$this->translate($this->errorMsgAuth, 'errors');?>
            </li>
        </ul>
    <?php endif;?>
    <?php
    $this->authForm->setAttribute('action', $this->url($this->getRoute()->route['controller'],
                                                array('lang'=>$this->getLang('code')),
                                                array('force_canonical'=>true)
                                )
    );
    echo $this->form()->openTag($this->authForm).PHP_EOL;
        echo '<fieldset data-role="fieldcontain" class="ui-wrapper-form">'.PHP_EOL;
            echo '<div class="ui-login"></div>';
            echo $this->formRow($this->authForm->get('login'), null, false).PHP_EOL;
            echo $this->formRow($this->authForm->get('type')).PHP_EOL;
            echo '<div class="ui-pass"></div>';
            echo $this->formRow($this->authForm->get('password'), null, false).PHP_EOL;
        echo '</fieldset>'.PHP_EOL;
        echo '<fieldset data-role="controlgroup" data-type="horizontal">'.PHP_EOL;
            echo $this->formRow($this->authForm->get('remember')).PHP_EOL;
            echo $this->formRow($this->authForm->get('submit')).PHP_EOL;
        echo '</fieldset>'.PHP_EOL;
    echo $this->form()->closeTag().PHP_EOL;
    ?>
</div>
<!-- Слой авторизации -->

