<!-- Слой восстановления аккаунта -->
<div id="restore" class="inner-tabs boxshadow">
    <?php
    echo $this->formElementerrors($this->restoreForm, array('class' => "ui-error")).PHP_EOL; // сообщение об ошибке
    ?>
    <?php if(!empty($this->successMsgRestore)):?>
        <ul class="ui-success">
            <li>
                <?=$this->translate($this->successMsgRestore, 'success');?>
            </li>
        </ul>
    <?php endif;?>
    <?php if(!empty($this->errorMsgRestore)):?>
        <ul class="ui-error">
            <li>
                <?php (isset($this->floodTime) && $this->floodTime > 0) ? printf($this->translate($this->errorMsgRestore, 'errors'), $this->setString('secondsformat', $this->floodTime)) : $this->translate($this->errorMsgRestore, 'errors'); ?>
            </li>
        </ul>
    <?php endif;?>
    <?php
    $this->restoreForm->setAttribute('action', $this->url($this->getRoute()->route['controller'],
                                                array('lang'=>$this->getLang('code')),
                                                array('force_canonical'=>true)
                                )
    );
    echo $this->form()->openTag($this->restoreForm).PHP_EOL;
        echo '<fieldset data-role="fieldcontain" class="ui-wrapper-form">'.PHP_EOL;
            echo '<div class="ui-login"></div>';
            echo $this->formRow($this->restoreForm->get('resign'), null, false).PHP_EOL;
            echo $this->formRow($this->restoreForm->get('type')).PHP_EOL;
        echo '</fieldset>'.PHP_EOL;
        echo '<fieldset data-role="controlgroup" data-type="horizontal">'.PHP_EOL;
                echo $this->formRow($this->restoreForm->get('csrf')).PHP_EOL;
                echo $this->formRow($this->restoreForm->get('submit')).PHP_EOL;
        echo '</fieldset>'.PHP_EOL;
    echo $this->form()->closeTag().PHP_EOL;
    ?>
</div>
<!-- Слой восстановления аккаунта -->
