<!-- Правила пользования социальной сетью -->
<section id="<?php echo $params['system'];?>" data-role="page" data-theme="a">
    <header data-role="header" data-theme="a">
        <h1><?php printf($params['title'], $this->translate('Social Mobile', 'default'));?></h3>
    </header>
    <div data-role="content" data-theme="b">
            <?=$params['description'];?>
    </div>
    <footer data-role="footer" class="ui-bar" data-theme="a">
    </footer>
</section>
<!-- Правила пользования социальной сетью -->

