<?php
/**
 * Перевод основного модуля
 * Language: Русский язык
 * Domain: social (default)
 * Author: Stanislav WEB
 */

return array(

	'Social Mobile'             =>  'Социальная Сеть',
        'Home'                  =>  'Главная',
        'Menu'                  =>  'Меню',
        'Here are %s users!'    =>  'Нас уже %s!',
        'Look for...'           =>  'Найти',
        'Photos'                =>  'Фото',
        'Online'                =>  'Онлайн',
        'Search'                =>  'Поиск',
        'Choose gender'         =>  'Выберите пол',
        'Male'                  =>  'Мужской',
        'Female'                =>  'Женский',
        'Last users'            =>  'Новые лица на сайте',
        'Sign in'               =>  'Присоединиться',
        'powered by'            =>  'сделана на',
        'All rights reserved.'  =>  'Все права защищены.',
        'Choose a language'     =>  'Выберите язык',
        'Russian'               =>  'Русский',
        'Ukrainian'             =>  'Українська',
        'English'               =>  'English',
        'Who is Online?'        =>  'Кто в онлайне?',
        'Girls'                 =>  'Девушки',
        'Guys'                  =>  'Парни',
    
        // Формы

        'Registration'          =>  'Регистрация',
        'Authorization'         =>  'Авторизация',
        'Access recovery'       =>  'Не помнишь пароль?',
        'Nobody at this time...'           =>  'На данный момент никого нет...',
        'Password'              =>  'Пароль',
        'Wishes password'       =>  'Желаемый пароль',
        'Register me'           =>  'Зарегистрировать меня',
        'Exit'                  =>  'Выход',
        'Rules and terms of use "%s"' =>  'Ознакомление с правилами использования Социальной сети "%s"',
        'I read the rules and agree to the terms'   =>  'Я прочитал правила и согласен со всеми условиями',
        'E-mail or mobile'      => 'E-mail или мобильный',
        'Your email or a mobile number'  => 'Введите ваш e-mail или мобильный',
        'Do remember my login?' => 'Запомнить меня?',
        'Login'                 => 'Войти',
        'Logout'                => 'Выйти',
        'Accept'                => 'Принять',
        'Back'                  => 'Вернуться',
        'Next'                  => 'Далее',
        'Setup your basic profile. Step 1'       => 'Заполнените анкету для вашей персональной страницы. Шаг 1',
        'Setup your basic profile. Step 2'       => 'Заполнените анкету для вашей персональной страницы. Шаг 2',
        'Finaly step of registration'           => 'Последний шаг регистрации',
        'Complete and Login automaticaly'       => 'Сохранить и авторизироваться',
        'Your profile picture'  => 'Фото карточка',
        'Your display name'     =>  'Ваше имя',
        'You can specify an actual name or nickname'    =>  'Вы можете использовать Ваше имя или придумать никнейм',
        'Date of birthday (year-month-day)'      => 'Дата рождения (год-месяц-день)',
        'Leave empty if you will not to show your age' =>  'Оставьте пустым, если нет желания указать свой возраст',
        "Date of birthday format is wrong. Try like this 1995-08-20" =>  'Не правильнный ввод даты рождения. Попробуйте так 1995-08-20',
        'Choose country'        => 'Выберите страну',
        'Choose region'         => 'Выберите регион',
        'Choose city'           => 'Выберите населенный пункт',
        'This field is required and process the recovery you access!'   => 'Это поле обязательно!',
        'Your new password for access'  => 'Ваш новый пароль',
        'Login that you used when registering'  => 'Логин, который вы указывали при регистрации',
        'New password'  => 'Новый пароль',
        'Your secret key'  =>  'Секретный ключ',
        'Reset'     =>  'Сбросить',
        'Setup new password'    =>  'Восстановление пароля',
        'Your email'            =>  'Ваш email',
        'Your recovery key'     =>  'Ваш ключ',
        'Whats Up?'             =>  'Как дела?',
        'Post on a wall'        =>  'Опубликовать на стене',
        'Share It!'             =>  'Сохранить',
    
	// Карта 
    
	'Search for friends here on this Map!'  =>  'Найди друзей на карте',
	'Looking for friends...'		=>  'Найти своих друзей...',
    
        // Короткие

        'month'   =>  'мес.',
        'months'   =>  'мес.',
        'day'   =>  'день',
        'days'   =>  'дня',
        'hour'   =>  'ч.',
        'hours'   =>  'ч.',
        'min.'   =>  'мин.',
        'sec.'   =>  'сек.',
    
        // Пользователь Анкета
    
        'Register date'     =>  'Дата регистрации',
        'My last visit'     =>  'Мой последний визит',
        'I stayed online'   =>  'Время в онлайне',
    
        // Подсказки

        'Login field is required and must contain your real mobile or email!'   => 'Логин должен быть Вашим реальным номером телефона или email',
        'Please setup something realy stronger! A\'int worry about, anytime you can reset it'   => 'Составте надежный пароль для вашего профиля. В любое время, Вы сможете его поменять или сбросить в случае утраты.',
        'After the submit you shall be read SMS or email box then activate a new access'    =>  'После сброса пароля, Вам на мобильный или почтовый ящик придет ссылка на сброс Вашего пароля',
        'This field is required and must contain your future Login for authenticate'        =>  'Это поле обязательно. Оно будет служить Вашим будущим логином при авторизации',
        'We need your password access :)'  =>  'Укажите Ваш пароль. Это обязательно',
        'This field is required'        =>  'Это поле обязательно к заполению',
        'Choose is required'            =>  'Обязательно выберите Ваш пол',
        'Please setup your realy date of birthday. Course if you wish to be founded in a Search'  => 'Желательно указать реальную дату рождения, чтобы Вас смогли потом найти в поиске',
        'Setup your realy country. This is will easy way to found you here'      =>  'Выберите Вашу страну. Это облегчит возможность найти Вас',
        'Setup your realy region. This is will easy way to found you here'  =>  'Выберите Ваш регион. Это облегчит возможность найти Вас',
        'Setup your realy city. This is will easy way to found you here'  =>  'Выберите Ваш населенный пункт. Это облегчит возможность найти Вас',
        'You can get your profile avatar'   =>  'Сдесь Вы можете установить себе аватар',



        // Системные

        'A 404 error occurred'  =>  'Ошибка 404. Страница не найдена',
        'An error occurred'     =>  'Произошла ошибка',
        'Additional information'           =>  'Дополнительная информация',
        'File'                  =>  'Файл',
        'Message'               =>  'Сообщение',
        'Stack trace'           =>  'Стек',
        'Previous exceptions'   =>  'Предыдущие исключения',
        'No Exception available'           =>  'Нет имеющихся исключений',
        'The requested controller was unable to dispatch the request'           =>  'Запрашиваемый контроллер не смог отправить запрос.',
        'The requested controller could not be mapped to an existing controller class.'           =>  'Запрашиваемый контроллер не может быть сопоставлен с существующими классом контроллера.',
        'The requested controller was not dispatchable.'           =>  'Запрашиваемый контроллер не доступен.',
        'The requested URL could not be matched by routing.'       =>  'Для запрашиваемого URL не может быть достигнуто направление.',
        'We cannot determine at this time why a 404 was generated.'           =>  'Мы не можем определить причину создания страницы 404.',
        'Controller'            =>  'Контроллер',
        'resolves to %s'        =>  'разрешает для %s',
        'Exception'             =>  'Исключение',
    );