<?php
/**
 * Перевод основного модуля
 * Language: Українська мова
 * Domain: social (default)
 * Author: Stanislav WEB
 */

return array(
        'Social Mobile'         =>  'Суцільна мережа',
        'Home'                  =>  'Головна',
        'Menu'                  =>  'Меню',
        'Here are %s users!'    => 'Нас вже %s!',
        'Look for...'           =>  'Вкажіть що або кого шукаєте',
        'Photos'                =>  'Фото',
        'Online'                =>  'Онлайн',
        'Search'                =>  'Пошук',
        'Choose gender'         =>  'Оберіть стать',
        'Male'                  =>  'Чоловіча',
        'Female'                =>  'Жіноча',
        'Last users'            =>  'Останні зареєстровані',
        'Sign in'               =>  'Приєднатися',
        'powered by'            =>  'зроблено на',
        'All rights reserved.'  =>  'Усі права запатентовані.',
        'Choose a language'     =>  'Оберіть мову',
        'Russian'               =>  'Русский',
        'Ukrainian'             =>  'Українська',
        'English'               =>  'English',
        'Who is Online?'        =>  'Хто в онлайні?',
        'Girls'                 =>  'Дівчата',
        'Guys'                  =>  'Хлопці',
    
        // Формы

        'Registration'          =>  'Реєстрація',
        'Authorization'         =>  'Авторизація',
        'Access recovery'       =>  'Не можеш увійти?',
        'Nobody at this time...'           =>  'Зараз тут нікого немає...',
        'Password'              =>  'Пароль',
        'Wishes password'       =>  'Бажаний пароль',
        'Register me'           =>  'Зареєтрувати мене',
        'Exit'                  =>  'Вийти',
        'I read the rules and agree to the terms'   =>  'Я прочитав правила та згоден з усіма умовами',
        'Rules and terms of use "%s"'   =>  'Правила поведінки та користування Суцільною мережею "%s"',
        'E-mail or mobile'      => 'E-mail або мобільний',
        'Your email or a mobile number'  => 'Введіть ваш e-mail або мобільний номер',
        'Do remember my login?' => 'Запам\'ятати мене?',
        'Login'                 => 'Увійти',
        'Logout'                => 'Вийти',
        'Accept'               => 'Відновити',
        'Back'                  => 'Назад',
        'Next'                  => 'Далі',
        'Setup your basic profile. Step 1'       => 'Заповніть анкету для вашої приватної сторінки. Шаг 1',
        'Setup your basic profile. Step 2'       => 'Заповніть анкету для вашої приватної сторінки. Шаг 2',
        'Finaly step of registration'           => 'Останній крок регістрації',
        'Your profile picture'  => 'Фото картка',
        'Complete and Login automaticaly'   => 'Створити мою сторінку',
        'Your display name'     =>  'Ваше ім\'я',
        'You can specify an actual name or nickname'    =>  'Вы можете використовувати ваше ім\'я або придумати собі нік',
        'Date of birthday (year-month-day)'      => 'Дата народження (рік-місяць-день)',
        'Leave empty if you will not to show your age' =>  'Залиште це, якщо нема бажання показувати свій рік',
        "Date of birthday format is wrong. Try like this 1995-08-20" =>  'Дата народження у невірному форматі. Спробуйте так 1995-08-20',
        'Choose country'        => 'Оберіть країну',
        'Choose region'         => 'Оберіть регіон',
        'Choose city'           => 'Оберіть ваше місце поселення',
        'Your email'            =>  'Ваш email',
        'Your recovery key'     =>  'Ваш ключ',
        'Whats Up?'             =>  'Як справи?',
        'Post on a wall'        =>  'На стіну',
        'Share It!'             =>  'Зберігти',
        'Your new password for access'  => 'Ваш новий пароль',
        'Login that you used when registering'  => 'Логін, який Ви реєстрували',
        'New password'  => 'Новий пароль',
        'Your recovery key'  =>  'Секретний ключ',
        'Reset'     =>  'Відправити',
        'Setup new password'    =>  'Відновлення пароля',
        'This field is required and process the recovery you access!'   => 'Це поле обов\'язково!',
    
	// Карта 
    
	'Search for friends here on this Map!'  =>  'Знайди друзів на карті',
	'Looking for friends...'		=>  'Знайти своїх друзів...',
	// Короткие
    
        'month'   =>  'міс.',
        'months'   =>  'міс.',
        'day'   =>  'день',
        'days'   =>  'дня',
        'hour'   =>  'год.',
        'hours'   =>  'год.',
        'min.'   =>  'хв.',
        'sec.'   =>  'сек.',

        // Подсказки
    
    
        // Пользователь Анкета
    
        'Register date'     =>  'Дата реєстрації',
        'My last visit'     =>  'Мій останній візит',
        'I stayed online'   =>  'В онлайні',    

        'Login field is required and must contain your real mobile or email!'   => 'Логін повинен бути Вашим реальним номером телефона або email\'ом',
        'Please setup something realy stronger! A\'int worry about, anytime you can reset it'   => 'Ваш пароль повинен бути міцним. У будь який час, Ви зможете його змінити або скинути якщо загубили.',
        'After the submit you shall be read SMS or email box then activate a new access'    =>  'Після того як Ви замовите відновлення пароля, Вам на мобільний або email прийде силка на відновлення',
        'This field is required and must contain your future Login for authenticate'        =>  'Логін обов\'язковий',
        'We need your password access :)'  =>  'Пароль також обов\'язковий',
        'This field is required'        =>  'Обов\'язково для введення',
        'Choose is required'            =>  'Обов\'язково оберіть Вашу стать',
        'Please setup your realy date of birthday. Course if you wish to be founded in a Search'  => 'Бажана дійсна дата народження, якщо Ви бажаєте щоб Вас могли знайти у пошуку',
        'Setup your realy country. This is will easy way to found you here'      =>  'Оберіть Вашу країну. Це замітно скоротить час на Ваш пошук',
        'Setup your realy region. This is will easy way to found you here'  =>  'Оберіть Ваш регіон. Це замітно скоротить час на Ваш пошук',
        'Setup your realy city. This is will easy way to found you here'  =>  'Оберіть Ваш населений пункт. Це замітно скоротить час на Ваш пошук',
        'You can get your profile avatar'   =>  'Якщо необхідно, завантажте свій аватар',

        // Системные

        'A 404 error occurred'  =>  'Помилка 404. Сторінка не найдена',
        'An error occurred'     =>  'Помилка у системі',
        'Additional information'           =>  'Додаткова інформація',
        'File'                  =>  'Файл',
        'Message'               =>  'Повідомлення',
        'Stack trace'           =>  'Розгорнутий стек',
        'Previous exceptions'   =>  'Попередня помилка',
        'No Exception available'           =>  'Помилок не знайдено',
        'The requested controller was unable to dispatch the request'           =>  'Контролер, який ви запросили не може здійснити запрос',
        'The requested controller could not be mapped to an existing controller class.'           =>  'Контролер, який ви запросили не може бути сопоставлений з цим класом.',
        'The requested controller was not dispatchable.'           =>  'Доступ до цього контролеру заборонений.',
        'The requested URL could not be matched by routing.'       =>  'Для цього URL не знайдено сопоставлення.',
        'We cannot determine at this time why a 404 was generated.'           =>  'Причина 404 помилки не відома.',
        'Controller'            =>  'Контролер',
        'resolves to %s'        =>  'дозволяє для %s',
        'Exception'             =>  'Виключення',
    );