<?php
/**
 * Перевод сообщений об ошибках
 * Language: Русский язык
 * Domain: success
 * Author: Stanislav WEB
 */

return array(

    // Слой восстановления пароля
    "Instructions for restoration of the password has been sent on your email"    =>  'Инструкция по восстановлению пароля была отправлена Вам на почту',
    "Instructions for restoration of the password has been sent on your mobile"    =>  'Инструкция по восстановлению пароля была отправлена по SMS',
);
