<?php
/**
 * Перевод сообщений об ошибках
 * Language: Українська мова
 * Domain: success
 * Author: Stanislav WEB
 */

return array(
    // Слой відновлення паролю
    "Instructions for restoration of the password has been on your email"    =>  'Інструкція з відновлення пароля була відправлена ​​Вам на пошту',
    "Instructions for restoration of the password has been on your mobile"    =>  'Інструкція з відновлення пароля була відправлена ​​Вам на мобільний',
);
