<?php

// Generated by ZF2's ./bin/templatemap_generator.php
return [
    'admin/sign/login'      => __DIR__ . '/view/admin/sign/login.phtml',
    'admin/admin/index'     => __DIR__ . '/view/admin/admin/index.phtml',
    'admin/admin/users'     => __DIR__ . '/view/admin/admin/users.phtml',
    'admin/admin/plugins'   => __DIR__ . '/view/admin/admin/plugins.phtml',
    'admin/plugins/index'   => __DIR__ . '/view/admin/plugins/index.phtml',
    'admin/plugins/view'    => __DIR__ . '/view/admin/plugins/view.phtml',
    'error/404'             => __DIR__ . '/view/error/404.phtml',
    'error/index'           => __DIR__ . '/view/error/index.phtml',
    'layout/admin'          => __DIR__ . '/view/layout/admin.phtml',
    'layout/pagination'     => __DIR__ . '/view/layout/pagination.phtml',
];
