<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'admin/admin/auth'  => __DIR__ . '/view/admin/admin/auth.phtml',
    'admin/admin/index' => __DIR__ . '/view/admin/admin/index.phtml',
    'admin/admin/users' => __DIR__ . '/view/admin/admin/users.phtml',
    'error/404'         => __DIR__ . '/view/error/404.phtml',
    'error/index'       => __DIR__ . '/view/error/index.phtml',
    'layout/admin'      => __DIR__ . '/view/layout/admin.phtml',
);
