    <div data-role="content" data-theme="a">
        <div class="ui-items-body">
            <div class="ui-hover-title">
                 <?php echo $this->navigation('navigation')->breadcrumbs()->setTranslatorTextDomain('admin')->setMinDepth(0)->setSeparator(' ▶ '); ?>
            </div> 
            <!-- Вывод мессенджера -->
                <?php echo $this->flashMessenger()->render('error', array('ui-error')); ?>
                <?php echo $this->flashMessenger()->render('success', array('ui-success')); ?>
            <!-- Вывод мессенджера -->		    
	    <!-- Таблица плагина -->
            <link href="<?php echo $this->basePath().'/css/tables.css'; ?>" media="screen" rel="stylesheet" type="text/css">
	    <form method="post">
               <table class="ui-table" data-theme="a" border="1">
                    <tbody>
			<tr class="ui-even">
                            <td>
                                <?php echo $this->translate('Title', 'admin');?>
                            </td>
                            <td>
                                <input type="text" name="title" placeholder="<?php echo $this->translate('Enter the name of the plugin', 'plugins');?>" data-clear-btn="true" autofocus="autofocus" data-mini="true" value="" required>
                            </td>
                        </tr>
                        <tr class="ui-odd">
                            <td>
                                <?php echo $this->translate('Description', 'admin');?>
                            </td>
                            <td>
                                <input type="text" name="description" placeholder="<?php echo $this->translate('Brief description of the plugin', 'plugins');?>" data-clear-btn="true" data-mini="true" value="" required>
                            </td>
                        </tr>
                        <tr class="ui-even">
                            <td>
                                <?php echo $this->translate('System', 'admin');?>
                            </td>
                            <td>
                                <input type="text" name="system" placeholder="<?php echo $this->translate('The code in which a plug can be identified', 'plugins');?>" data-clear-btn="true" data-mini="true" value="" required>
                            </td>
                        </tr>                        
                        <tr class="ui-odd">
                            <td>
                                <?php echo $this->translate('Type', 'admin');?>
                            </td>
                            <td>
                                <select name="type" id="type" data-mini="true" required>
                                    <option value=""><?php echo $this->translate('Typing your plugin', 'plugins');?></option>
                                    <?php foreach($filter as $v): ?>
                                    <option value="<?php echo $v['id']; ?>"><?php echo $v['name']; ?></option>
                                    <?php endforeach; ?>
                                </select>                                
                            </td>
                        </tr>     
                        <tr class="ui-even">
                            <td>
                                <?php echo $this->translate('Status', 'admin');?>
                            </td>
                            <td>
                                <select name="status" id="status" data-mini="true" required>
                                    <option value=""><?php echo $this->translate('Set activity status', 'plugins');?></option>
                                    <option value="0"><?php echo $this->translate('off' , 'admin'); ?></option>
                                    <option value="1"><?php echo $this->translate('active' , 'admin'); ?></option>
                                </select>     
                            </td>
                        </tr>     
                        <tr class="ui-odd">
                            <td>
                                <?php echo $this->translate('Mode', 'admin');?>
                            </td>
                            <td>
                                <label for="readonly"><?php echo $this->translate('Set readonly mode (read - mosly system plugins)', 'plugins');?></label>
                                <input type="checkbox" name="readonly" id="readonly" data-mini="true" value="1">
                            </td>
                        </tr>                           
                        <tr class="tfoot">
                            <td colspan="2">
                                <fieldset data-role="controlgroup" data-type="horizontal"> 
                                    <label>
                                        <input type="submit" data-inline="true" data-icon="arrow-d" data-mini="true" value="<?php echo $this->translate('Add this', 'admin');?>">
                                    </label>
                                </fieldset>
                            </td>
                        </tr>
                    </tbody>                      
                </table>
	    </form>
            <?php echo $this->flashMessenger()->render('info', array('ui-info')); ?>
	    <!-- Таблица плагина -->
        </div>
    </div>