    <div data-role="content" data-theme="a">
        <div class="ui-items-body">
            <div class="ui-hover-title">
                 <?php echo $this->navigation('navigation')->breadcrumbs()->setTranslatorTextDomain('admin')->setMinDepth(0)->setSeparator(' ▶ '); echo $title; ?>  
            </div>         
            <!-- Вывод мессенджера -->
                <?php echo $this->flashMessenger()->render('error', array('ui-error')); ?>
                <?php echo $this->flashMessenger()->render('success', array('ui-success')); ?>
            <!-- Вывод мессенджера -->		    
	    <!-- Таблица плагина -->
            <link href="<?php echo $this->basePath().'/css/tables.css'; ?>" media="screen" rel="stylesheet" type="text/css">
            <?php $disable   =   ($item->readonly) ? 'disabled' : ''; ?>
	    <form method="post">
               <input type="hidden" name="readonly" value="<?php echo $item->readonly;?>">
               <table class="ui-table" data-theme="a" border="1">
                    <tbody>
			<tr class="ui-even">
                            <td>
                                <?php echo $this->translate('Title', 'admin');?>
                            </td>
                            <td>
                                <input type="text" name="title" data-clear-btn="true" autofocus="autofocus" data-mini="true" value="<?php echo $item->title;?>" <?php echo $disable; ?> required>
                            </td>
                        </tr>
                        <tr class="ui-odd">
                            <td>
                                <?php echo $this->translate('Description', 'admin');?>
                            </td>
                            <td>
                                <input type="text" name="description" data-clear-btn="true" data-mini="true" value="<?php echo $item->description;?>" <?php echo $disable; ?> required>                                
                            </td>
                        </tr>
                        <tr class="ui-even">
                            <td>
                                <?php echo $this->translate('System', 'admin');?>
                            </td>
                            <td>
                                <input type="text" name="system" data-clear-btn="true" data-mini="true" value="<?php echo $item->system;?>" <?php echo $disable; ?> required>
                            </td>
                        </tr>                        
                        <tr class="ui-odd">
                            <td>
                                <?php echo $this->translate('Type', 'admin');?>
                            </td>
                            <td>
                                <select name="type" id="type" data-mini="true" <?php echo $disable; ?> required>
                                    <?php foreach($filter as $v): ?>
                                    <option value="<?php echo $v['id']; ?>" <?php echo ($v['id'] == $item->type) ? 'selected': ''; ?>><?php echo $v['name']; ?></option>
                                    <?php endforeach; ?>
                                </select>                                
                            </td>
                        </tr>     
                        <tr class="ui-even">
                            <td>
                                <?php echo $this->translate('Status', 'admin');?>
                            </td>
                            <td>
                                <select name="status" id="status" data-mini="true" <?php echo $disable; ?> required>
                                    <option value="0" <?php echo ($item->status == 0) ? 'selected': ''; ?>><?php echo $this->translate('off' , 'admin'); ?></option>
                                    <option value="1" <?php echo ($item->status == 1) ? 'selected': ''; ?>><?php echo $this->translate('active' , 'admin'); ?></option>
                                </select>     
                            </td>
                        </tr>                         
                        <tr class="tfoot">
                            <td colspan="2">
                                <fieldset data-role="controlgroup" data-type="horizontal"> 
                                    <label>
                                        <input type="submit" data-inline="true" data-icon="arrow-d" data-mini="true" value="<?php echo $this->translate('Save params', 'admin');?>" <?php echo $disable; ?>>
                                    </label>
                                </fieldset>
                            </td>
                        </tr>
                    </tbody>                      
                </table>
	    </form>
            <?php echo $this->flashMessenger()->render('info', array('ui-info')); ?>
	    <!-- Таблица плагина -->
        </div>
    </div>