    <div data-role="content" data-theme="a">
        <div class="ui-items-body">
            <div class="ui-hover-title">
               <?php echo $this->navigation('navigation')->breadcrumbs()->setTranslatorTextDomain('admin')->setMinDepth(0)->setSeparator(' ▶ '); ?>             
            </div>           
            <?php if(!empty($filter)): ?>
            <!-- Фильтры -->
            <div class="ui-grid-a">
                <div class="ui-block-a">
                    <form action="" method="get" name="type" data-ajax="false" id="type">
                        <fieldset data-role="controlgroup" data-type="horizontal">
                            <a href="/admin/plugins/add" data-mini="true" data-role="button"><?php echo $this->translate('Register plugin', 'admin');?></a>
                            <select name="type" id="type" data-mini="true">
                                <option value="" selected="selected"><?php echo $this->translate('Filter: Please choise type' , 'plugins');?></option>
                                <?php foreach($filter as $v): ?>
                                <option value="<?php echo $v['id']; ?>"><?php echo $v['name']; ?></option>
                                <?php endforeach; ?>
                            </select>
                            <input type="submit" data-inline="true" data-icon="search" data-mini="true" value="<?php echo $this->translate('Show' , 'plugins');?>">
                        </fieldset>
                    </form>
                </div>
            </div>            
            <!-- Фильтры -->
            <?php endif; ?>
            <!-- Вывод мессенджера -->
                <?php echo $this->flashMessenger()->render('error', array('ui-error')); ?>
                <?php echo $this->flashMessenger()->render('success', array('ui-success')); ?>
            <!-- Вывод мессенджера -->
	    <!-- Таблица плагинов -->
            <link href="<?php echo $this->basePath().'/css/tables.css'; ?>" media="screen" rel="stylesheet" type="text/css">
	    <form method="post">
                <table class="ui-table" data-theme="a" border="1">
                    <thead class="ui-table-hover">
                        <tr>
                            <th>
                                <label for="all"><?php echo $this->translate('All' , 'admin');?></label>
                                <input type="checkbox" name="all" id="all" data-mini="true" value="1">
                            </th>
                            <th>
                                <span><?php echo $this->translate('Title' , 'plugins');?></span>
                            </th>                                
                            <th>
                                <span><?php echo $this->translate('Description' , 'plugins');?></span>
                            </th>                                
                            <th>
                                <span><?php echo $this->translate('System code' , 'plugins');?></span>
                            </th>
                            <th>
                                <span><?php echo $this->translate('Status' , 'plugins');?></span>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $i = 0; foreach($items as $item):?>
			<?php $class	=   ($i++ % 2 == 0) ? 'ui-even' : 'ui-odd'; ?>
			<tr class="<?php echo $class?>">
                            <td>
                                <fieldset data-role="controlgroup" data-type="horizontal">
                                    <label for="select-<?php echo $item['id']?>"><?php echo $item['id']?></label>
                                    <input title="<?php echo $this->translate('Check this' , 'plugins');?>" type="checkbox" name="select[]" id="select-<?php echo $item['id']?>" data-mini="true" value="<?php echo $item['id']?>">
                                    <a data-role="button" title="<?php echo $this->translate('edit' , 'plugins');?>" data-mini="true" href="/admin/plugins/edit/<?php echo $item['id'];?>"><?php echo $this->translate('edit' , 'plugins');?></a>
                                </fieldset>
                            </td>
                            <td>
                                <a href="/admin/plugins/edit/<?php echo $item['id'];?>"><?php echo $item['title']?></a> 
                            </td>
                            <td>
                                <?php echo $item['description'];?>
                            </td>
                            <td>
                                <?php echo $item['system'];?>
                            </td>
                            <td class="ui-center">
                                <span data-role="button" data-mini="true" disabled="disabled" class="ui-status-container <?php echo ($item['status'] != 0) ? 'ui-green' : 'ui-red';?>">
                                    <?php echo ($item['status'] != 0) ? $this->translate('active' , 'admin') : $this->translate('off' , 'admin');?>
                                </span>
                            </td>
			</tr>
			<?php endforeach;?>
                        <tr class="tfoot">
                            <td colspan="5">
                                <!-- Навигация -->
                                <?php echo (count($items) > 0) ? $this->paginationControl($items, 'sliding', 'plugins/admin-pager') : '' ?>
                                <!-- Навигация -->
                                <!-- Панель управления CRUD -->
                                <fieldset data-role="controlgroup" data-type="horizontal"> 
                                    <legend><?php echo $this->translate('What to do with markup ?', 'admin');?></legend>
                                    <label>
                                        <?php echo $this->translate('On', 'admin');?><input id="onAction" type="radio" name="action" data-inline="true" data-mini="true" value="onAction">
                                    </label>  
                                    <label>
                                        <?php echo $this->translate('Off', 'admin');?><input id="offAction" type="radio" name="action" data-inline="true" data-mini="true" value="offAction">
                                    </label>                             
                                    <label>
                                        <?php echo $this->translate('Delete', 'admin');?><input id="deleteAction" type="radio" name="action" data-inline="true" data-mini="true" value="deleteAction">
                                    </label>                            
                                    <input type="submit" data-inline="true" data-icon="arrow-d" data-mini="true" value="<?php echo $this->translate('Do it!', 'admin');?>">
                                </fieldset>
                                <!-- Панель управления CRUD -->                                     
                            </td>
                        </tr>
                    </tbody>                      
                </table>
	    </form>
	    <!-- Таблица пользователей -->	    
        </div>
    </div>