<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'locations/locations/index'	   => __DIR__ . '/view/locations/index.phtml',
    'locations/locations/long'	   => __DIR__ . '/view/locations/long.phtml',
    'locations/locations/short'    => __DIR__ . '/view/locations/short.phtml',
);
