<div data-role="content" data-theme="a">
    <div class="ui-admin-body">
        <div class="ui-hover-title">
            <?php echo $this->navigation('navigation')->breadcrumbs()->setTranslatorTextDomain('admin')->setMinDepth(0)->setSeparator(' ▶ '); ?>
        </div>
        <!--<div class="ui-admin-top">
        <?php //echo $this->socialPlugin('menu', 'admin-nav-menu'); // верхнее меню ?>
        </div>-->
        <!-- Вывод мессенджера -->
        <?php echo $this->flashMessenger()->render('error', array('ui-error')); ?>
        <?php echo $this->flashMessenger()->render('success', array('ui-success')); ?>
        <!-- Вывод мессенджера -->	    
        <div class="ui-grid-a">
            <div class="ui-block-a">
                <?php echo $this->socialPlugin('menu', 'admin-main-menu'); // главное меню админа ?>
            </div>
            <div class="ui-block-b">
                <?php echo $this->socialPlugin('menu', 'admin-info-menu'); // меню с информацией о системе?>
            </div>                
        </div>
        <!--<div class="ui-admin-bottom">
        <?php //echo $this->socialPlugin('menu', 'admin-status-menu'); // панель состояния ?>                
        </div>-->
    </div>
</div>