<section data-role="page" data-theme="a">
    <header data-role="header" data-theme="a" data-position="fixed" class="ui-admin-header">
        <div class="ui-grid-a">
            <div class="ui-block-a">
                <a href="#Language" title="<?=$this->translate('Choose a language' , 'default');?>" class="ui-hover-btn ui-admin-nav-btn" data-role="button" data-rel="dialog"><img src="/images/flags/small/<?=$this->getLang('code');?>.png" alt="<?=$this->getLang('code');?>" /></a>
                <a href="#" id="login" title="Администратор" class="ui-hover-btn ui-admin-nav-btn" data-role="button" data-rel="dialog"><img src="/images/admin/admin.gif" alt="Администратор" />&nbsp;&nbsp;<span><?php echo $this->user->name?></span></a>                
            </div>
            <div class="ui-block-b">
                <h1 class="ui-admin-logo">
                    <a href="<?=$this->url('social' , ['lang' => $this->getLang('code')] , ['force_canonical' => true]);?>"><img src="/images/mobile/logo.png" alt="Logo"></a>
                </h1>              
            </div>
            <div class="ui-block-c" align="right">
                <a href="#" class="ui-hover-btn ui-admin-nav-btn" data-role="button" onclick="return false;" id="clock" data-rel="dialog"></a>
                <a href="<?=$this->url('admin' , ['lang' => $this->getLang('code') ,'action' => 'logout'] , ['force_canonical' => true]);?>" title="<?=$this->translate('Logout' , 'admin');?>" class="ui-hover-btn ui-admin-nav-btn" data-transition="pop" data-role="button"><img src="/images/admin/mini_logout.png" alt="<?=$this->translate('Logout' , 'admin')?>" /></a>                
            </div>
        </div>
    </header>
    <div data-role="content" data-theme="a">
        <div class="ui-admin-users-body">
            <div class="ui-hover-title">
		<?=$this->translate('Plugins control' , 'admin');?>
            </div>
            <?php if(!empty($this->messages)):?>
            <ul class="ui-error">
                <?php foreach($this->messages as $message):?>
                <li>
                    <?=$this->translate($message, 'admin-errors');?>
                </li>
                <?php endforeach; ?>
            </ul>
            <?php endif;?>		    
	    <!-- Таблица пользователей -->
	    <form method="post">
		<div class="ui-grid-c ui-admin-users" data-theme="a" data-inset="true">
		    <div class="ui-admin-grid-hover">
			<div class="ui-block-a">
			    <label for="all"><?=$this->translate('All' , 'admin');?></label>
                            <input type="checkbox" name="all" id="all" data-mini="true" value="1">
			</div>
			<div class="ui-block-b"><span><?=$this->translate('Title' , 'plugins');?></span></div>
			<div class="ui-block-c"><span><?=$this->translate('Description' , 'plugins');?></span></div>
			<div class="ui-block-d"><span><?=$this->translate('Status' , 'plugins');?></span></div>
		    </div>
		    <div class="ui-admin-grid-content">
			<?php $i = 0; foreach($items as $item):?>
			    <?php 
			    $class	=   ($i++ % 2 == 0) ? 'ui-even' : 'ui-odd';
			    ?>
			    <div class="ui-block-a <?php echo $class?>">
				<div class="ui-admin-userinfo">
				    <label for="select-<?php echo $item['id']?>"><?php echo $item['id']?></label>
                                    <input type="checkbox" name="select[]" id="select-<?php echo $item['id']?>" data-mini="true" value="1">
				</div>
			    </div>
			    <div class="ui-block-b <?php echo $class?>">
                                <div class="ui-admin-userinfo">
				    <a href="plugins/<?php echo $item['id'];?>"><?php echo $item['title']?></a>
				</div>
			    </div>	
			    <div class="ui-block-c <?php echo $class?>">
				<?php echo $item['description'];?>
			    </div>			
			    <div class="ui-block-d <?php echo $class?>">
				<?php echo $item['status'];?>
			    </div>
			<?php endforeach;?>		    
		    </div>
		    <div class="ui-admin-grid-footer">
			<!-- Навигация -->
			<?php echo (count($items) > 0) ? $this->paginationControl($items, 'sliding', 'plugins/admin-pager') : '' ?>
			<!-- Навигация -->
			<fieldset data-role="controlgroup" data-type="horizontal"> 
			    <legend><?=$this->translate('What to do with markup ?', 'admin');?></legend>
			    <label for="Edit">Edit</label><input id="Edit" type="radio" name="do" data-inline="true" data-mini="true" value="Edit">
			    <label for="Block">Block</label><input id="Block" type="radio" name="do" data-inline="true" data-mini="true" value="Block">
			    <label for="Unblock">Unblock</label><input id="Unblock" type="radio" name="do" data-inline="true" data-mini="true" value="Unblock">
			    <label for="Status">Status</label><input id="Status" type="radio" name="do" data-inline="true" data-mini="true" value="Status">
			    <label for="Delete">Delete</label><input id="Delete" type="radio" name="do" data-inline="true" data-mini="true" value="Delete">
			    <input type="submit" data-inline="true" data-icon="arrow-d" data-mini="true" value="Do it!">
			</fieldset>
		    </div>
		</div>
	    </form>

	    <!-- Таблица пользователей -->	    
        </div>
    </div>
    <footer data-position="fixed" data-role="footer" class="ui-bar footer" data-theme="a">
        <h4>&copy; 2013  <a href="/"><?=$this->translate('Social Mobile' , 'default')?></a> <?=$this->translate('powered by' , 'default')?> <?=Zend\Version\Version::VERSION_SERVICE_ZEND;?> <?=Zend\Version\Version::VERSION;?> <?=$this->translate('All rights reserved.' , 'default')?></h4>
    </footer>
</section>
<?php echo $this->socialPlugin('language'); // виджет выбора языка ?>
