<?php $format = new \SW\String\Format;?>   
<section data-role="page" data-theme="a">
    <header data-role="header" data-theme="a" data-position="fixed" class="ui-admin-header">
        <div class="ui-grid-a">
            <div class="ui-block-a">
                <a href="#Language" title="<?php echo $this->translate('Choose a language' , 'default');?>" class="ui-hover-btn ui-admin-nav-btn" data-role="button" data-rel="dialog"><img src="/images/flags/small/<?php echo $this->getLang('code');?>.png" alt="<?php echo $this->getLang('code');?>" /></a>
                <a href="#" id="login" title="Администратор" class="ui-hover-btn ui-admin-nav-btn" data-role="button" data-rel="dialog"><img src="/images/admin/admin.gif" alt="Администратор" />&nbsp;&nbsp;<span><?php echo $this->user->name?></span></a>                
            </div>
            <div class="ui-block-b">
                <h1 class="ui-admin-logo">
                    <a href="<?php echo $this->url('social' , array(
    'lang' => $this->getLang('code')) , array(
    'force_canonical' => true));?>"><img src="/images/mobile/logo.png" alt="Logo"></a>
                </h1>              
            </div>
            <div class="ui-block-c" align="right">
                <a href="#" class="ui-hover-btn ui-admin-nav-btn" data-role="button" onclick="return false;" id="clock" data-rel="dialog"></a>
                <a href="<?php echo $this->url('admin' , array(
    'lang' => $this->getLang('code') ,
    'action' => 'logout') , array(
    'force_canonical' => true));?>" title="<?php echo $this->translate('Logout' , 'admin');?>" class="ui-hover-btn ui-admin-nav-btn" data-transition="pop" data-role="button"><img src="/images/admin/mini_logout.png" alt="<?php echo $this->translate('Logout' , 'admin')?>" /></a>                
            </div>
        </div>
    </header>
    <div data-role="content" data-theme="a">
        <div class="ui-items-body">
            <div class="ui-hover-title">
		<?php echo $this->translate('Users Control' , 'admin');?>
            </div>
            <?php if(!empty($this->errorMsg)):?>
            <ul class="ui-error">
                <?php foreach($this->errorMsg as $error):?>
                <li>
                    <?php echo $this->translate($error, 'admin-errors');?>
                </li>
                <?php endforeach; ?>
            </ul>
            <?php endif;?>		    
	    <!-- Таблица пользователей -->
	    <form action="<?php echo $this->url('admin-post');?>" method="post">
		<input type="hidden" name="controller" value="<?php echo $this->getRoute()->route['controller'];?>">
		<input type="hidden" name="action" value="<?php echo $this->getRoute()->route['action'];?>">
		<div class="ui-grid-d ui-items" data-theme="a" data-inset="true">
		    <div class="ui-admin-grid-hover">
			<div class="ui-block-a">
			    <label for="all"><?php echo $this->translate('All' , 'admin');?></label><input type="checkbox" name="all" id="all" data-mini="true" value="1">
			</div>
			<div class="ui-block-b"><span><?php echo $this->translate('User' , 'admin');?></span></div>
			<div class="ui-block-c"><span><?php echo $this->translate('Photo' , 'admin');?></span></div>
			<div class="ui-block-d"><span><?php echo $this->translate('Location' , 'admin');?></span></div>
			<div class="ui-block-e"><span><?php echo $this->translate('Information' , 'admin');?></span></div>		    
		    </div>
		    <div class="ui-admin-grid-content">
			<?php $i = 0; foreach($items as $user):?>
			    <?php 
			    $class	=   ($i++ % 2 == 0) ? 'ui-even' : 'ui-odd';
			    if($user['role_id'] > 0) $class = 'ui-prime';
			    $dateReg	= $format->getFormatTime($user['date_registration'] , $user['timezone']);
			    $dateLast	= $format->getFormatTime($user['date_lastvisit'] , $user['timezone']);
			    ?>
			    <div class="ui-block-a <?php echo $class?>">
				<div class="ui-admin-userinfo">
				    <label for="select-<?php echo $user['id']?>"><?php echo $user['id']?></label>
                                    <input type="checkbox" name="select[]" id="select-<?php echo $user['id']?>" data-mini="true" value="1">
				</div>
			    </div>
			    <div class="ui-block-b <?php echo $class?>">
				<div class="ui-admin-userinfo">
				    <a href="/user/<?php echo $user['id'];?>/"><span class="<?php if($user['gender'] == 2):?>ui-f<?php else:?>ui-m<?php endif;?>"></span> <?php echo $user['name']?></a>
				</div>
			    </div>	
			    <div class="ui-block-c <?php echo $class?>">
				<?php if($user['photo']):?>
				    <img class="ui-img-list" src="/files/images/thumb/<?php echo $user['id'];?>/<?php echo $user['photo'];?>" />
				<?php else:?>
				    <img class="ui-img-list" src="/images/mobile/<?php if($user['gender'] == 2):?>female.png<?php else:?>male.png<?php endif;?>" />
				<?php endif;?>
			    </div>			
			    <div class="ui-block-d <?php echo $class?>">
				<div class="ui-admin-userinfo">
				    <span class="ui-location-string"><img class="ui-small-flag" src="/images/flags/small/<?php echo strtolower($user['country_code']);?>.png" alt="" /> <?php echo $user['country'];?> » <?php echo $user['region'];?>, <?php echo $user['city'];?></span> 
				</div>
			    </div>
			    <div class="ui-block-e <?php echo $class?>">
				<div class="ui-admin-userinfo">
				    <span class="ui-admin-userid">
					<b><?php echo $this->translate('ID' , 'admin');?></b>
					<?php echo $user['id'] ;?>
				    </span>				    
				    <span class="ui-admin-userlogin">
					<b><?php echo $this->translate('Login' , 'admin');?></b>
					<?php echo $user['login'] ;?>
				    </span>	
				    <span class="ui-admin-usergroup">
					<b><?php echo $this->translate('Group' , 'admin');?></b>
					<?php echo $user['group_title'] ;?>
				    </span>				
				    <span class="ui-admin-userreg">
					<b><?php echo $this->translate('Register date' , 'admin');?></b>
					<?php echo $dateReg['d'] . ' ' . $this->translate($dateReg['m'] , 'plugins') . ' ' . $dateReg['y'] . ' ' . $dateReg['h'] . ':' . $dateReg['i'];?>
				    </span>
				    <span class="ui-admin-userlast">
					<b><?php echo $this->translate('Last visit date' , 'admin');?></b>
					<?php echo $dateLast['d'] . ' ' . $this->translate($dateLast['m'] , 'plugins') . ' ' . $dateLast['y'] . ' ' . $dateLast['h'] . ':' . $dateLast['i'];?>
				    </span>				    
				</div>
			    </div>
			<?php endforeach;?>		    
		    </div>
		    <div class="ui-admin-grid-footer">
			<!-- Навигация -->
			<?php echo (count($items) > 0) ? $this->paginationControl($items, 'sliding', 'plugins/pager') : '' ?>
			<!-- Навигация -->
			
			<fieldset data-role="controlgroup" data-type="horizontal"> 
			    <legend><?php echo $this->translate('What to do with markup ?', 'admin');?></legend>
			    <label for="Edit">Edit</label><input id="Edit" type="radio" name="do" data-inline="true" data-mini="true" value="Edit">
			    <label for="Block">Block</label><input id="Block" type="radio" name="do" data-inline="true" data-mini="true" value="Block">
			    <label for="Unblock">Unblock</label><input id="Unblock" type="radio" name="do" data-inline="true" data-mini="true" value="Unblock">
			    <label for="Status">Status</label><input id="Status" type="radio" name="do" data-inline="true" data-mini="true" value="Status">
			    <label for="Delete">Delete</label><input id="Delete" type="radio" name="do" data-inline="true" data-mini="true" value="Delete">
			    <input type="submit" data-inline="true" data-icon="arrow-d" data-mini="true" value="Do it!">
			</fieldset>
		    </div>
		</div>
	    </form>

	    <!-- Таблица пользователей -->	    
        </div>
    </div>
    <footer data-position="fixed" data-role="footer" class="ui-bar footer" data-theme="a">
        <h4>&copy; 2013  <a href="/"><?php echo $this->translate('Social Mobile' , 'default')?></a> <?php echo $this->translate('powered by' , 'default')?> <?php echo Zend\Version\Version::VERSION_SERVICE_ZEND;?> <?php echo Zend\Version\Version::VERSION;?> <?php echo $this->translate('All rights reserved.' , 'default')?></h4>
    </footer>
</section>
<?php echo $this->socialPlugin('language'); // виджет выбора языка ?>
