<?php echo $this->doctype().PHP_EOL;?>
<html lang="<?php echo $this->lang;?>" xmlns:og="http://ogp.me/ns#">
    <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb#">
        <?php
            // Устанавливаю правильный заголовок страницы
            if($this->serverUrl().'/' != $this->serverUrl(true)) 
                $this->headTitle($this->translate('Social Mobile', 'default'), "prepend")->setSeparator(' | ')->setAutoEscape(false);
            echo $this->headTitle();
        ?>
        <?php echo $this->headMeta()
                // META информация
                ->setCharset('UTF-8')
                ->appendName('viewport',        'width=device-width, initial-scale=1, maximum-scale=1')

                // Open Graph

                ->setProperty('og:title',        strip_tags($this->headTitle()))
                ->setProperty('og:type',         'article')
                ->setProperty('og:url',          $this->serverUrl(true))
                ->setProperty('og:image',        $this->serverUrl().'/images/mobile/logo.png')
                ->setProperty('og:site_name',    $this->translate('Social Mobile', 'default'))
                ->setProperty('og:description',  '');
        ?>
        <?php echo $this->headLink(array('rel'=>'shortcut icon', 'href'=>$this->basePath().'/images/favicon.ico')); ?>
        <?php echo $this->headScript(); ?>
    </head>
    <body>                    
        <?php echo $this->content;?>
    </body>
</html>