<section data-role="page" data-theme="a">
    <?php echo $this->socialPlugin('header'); // заголовок jQuery Mobile ?>
    <div data-role="content" data-theme="a">
        <nav data-role="navbar">
            <ul>
                <li><a href="javascript:;" class="ui-tab register" data-href="register"><?php echo $this->translate('Registration', 'default');?></a>
                <li><a href="javascript:;" class="ui-tab auth" data-href="auth"><?php echo $this->translate('Authorization', 'default');?></a>
                <li><a href="javascript:;" class="ui-tab restore" data-href="restore"><?php echo $this->translate('Access recovery', 'default');?></a>
            </ul>
        </nav>
        <!-- Вывод мессенджера -->
        <?php echo $this->flashMessenger()->render('error', array('ui-error')); ?>
        <?php echo $this->flashMessenger()->render('success', array('ui-success')); ?>
        <!-- Вывод мессенджера -->	        
        <?php echo $this->registerTemplate; // форма регистрации ?>
        <?php echo $this->authTemplate; // форма авторизации ?>
        <?php echo $this->restoreTemplate; // форма восстановления ?>
    </div>
    <footer data-position="fixed" data-role="footer" class="ui-bar footer" data-theme="a">
        <?php //echo $this->socialAuth(); ?>
        <?php echo $this->socialPlugin('bookmarks'); // виджет соц. закладок ?>
        <h4>&copy; 2013  <a href="/"><?php echo $this->translate('Social Mobile', 'default')?></a> <?php echo $this->translate('powered by', 'default')?> <?php echo Zend\Version\Version::VERSION_SERVICE_ZEND;?> <?php echo Zend\Version\Version::VERSION;?> <?php echo $this->translate('All rights reserved.', 'default')?></h4>
    </footer>
</section>
<?php
// Редирект на вкладку в случае ошибки формы
$redirect = $this->getRoute()->post('type');
if(isset($redirect))
{
    echo "<script type=\"text/javascript\">".PHP_EOL;
        echo "\$(document).ready(function(){
            \$('a[data-href=".$redirect."]').click();
        });".PHP_EOL;
    echo"</script>".PHP_EOL;
}
?>
<?php echo $this->socialPlugin('language'); // виджет выбора языка ?>
<?php echo $this->socialPlugin('notices', 'rules'); // виджет правил ?>

<?php echo $this->inlineScript()->appendFile($this->basePath().'/js/form.storage.js', 'text/javascript');?>
<?php echo $this->inlineScript()->appendFile($this->basePath().'/js/mobile/tooltip.js', 'text/javascript');?>