<!-- Слой установки пароля -->
<section data-role="page" data-theme="a">
    <?php echo $this->socialPlugin('header'); // заголовок jQuery Mobile ?>
    <div data-role="content" data-theme="a">
        <?php if(!empty($this->successMsg)):?>
        <ul class="ui-success">
            <li>
                <?=$this->translate($this->successMsg, 'success');?>
            </li>
        </ul>
        <?php endif;?>
        <?php if(!empty($this->errorMsg)):?>
            <ul class="ui-error">
                <li>
                    <?php echo $this->translate($this->errorMsg, 'errors'); ?>
                </li>
            </ul>
        <?php endif;?>
        <?php
        echo $this->formElementerrors($this->SetPasswordFormEmail, array('class' => "ui-error")).PHP_EOL; // сообщение об ошибке
        ?>
        <?php
        $this->SetPasswordFormEmail->setAttribute('action', $this->url($this->getRoute()->route['controller'],
                array('lang'=>$this->getLang('code')),
                array('force_canonical'=>true)
            )
        );
        echo $this->form()->openTag($this->SetPasswordFormEmail).PHP_EOL;
        echo '<fieldset data-role="fieldcontain" class="ui-wrapper-form">'.PHP_EOL;
        echo '<div class="ui-login"></div>';
        echo $this->formRow($this->SetPasswordFormEmail->get('login')->setValue($this->email), null, false).PHP_EOL;
        echo $this->formRow($this->SetPasswordFormEmail->get('restore')->setValue($this->restore), null, false).PHP_EOL;
        echo $this->formRow($this->SetPasswordFormEmail->get('csrf'), null, false).PHP_EOL;
        echo '<div class="ui-pass"></div>';
        echo $this->formRow($this->SetPasswordFormEmail->get('password'), null, false).PHP_EOL;
        echo '<div class="ui-pass"></div>';
        echo $this->formRow($this->SetPasswordFormEmail->get('restoreEmailCode')->setValue($this->keyString), null, false).PHP_EOL;
        echo '</fieldset>'.PHP_EOL;
        echo '<fieldset data-role="controlgroup" data-type="horizontal">'.PHP_EOL;
        echo $this->formRow($this->SetPasswordFormEmail->get('submit')).PHP_EOL;
        echo '</fieldset>'.PHP_EOL;
        echo $this->form()->closeTag().PHP_EOL;
        ?>
    </div>
    <footer data-position="fixed" data-role="footer" class="ui-bar footer" data-theme="a">
        <h4>&copy; 2013  <a href="/"><?=$this->translate('Social Mobile', 'default')?></a> <?=$this->translate('powered by', 'default')?> <?=Zend\Version\Version::VERSION_SERVICE_ZEND;?> <?=Zend\Version\Version::VERSION;?> <?=$this->translate('All rights reserved.', 'default')?></h4>
    </footer>
</section>
<?php echo $this->socialPlugin('language'); // виджет выбора языка ?>
<?=$this->inlineScript()->appendFile($this->basePath().'/js/mobile/tooltip.js', 'text/javascript');?>
<!-- Слой установки пароля -->
