<!-- Выбор месторасположения -->
<section data-role="page" data-theme="a">
    <?php echo $this->socialPlugin('header'); // заголовок jQuery Mobile ?>
    <div data-role="content" data-theme="a">
    <?
    echo $this->formElementerrors($this->registerProfileForm, array('class' => "ui-error")).PHP_EOL; // сообщение об ошибке

    $this->registerProfileForm->setAttribute('action', $this->url($this->getRoute()->route['controller'],
                                                array('action' => $this->getRoute()->route['action'],  'lang'=>$this->getLang('code')),
                                                array('force_canonical'=>true)
                                )
    );
    $this->registerProfileForm->prepare();
    echo $this->form()->openTag($this->registerProfileForm).PHP_EOL;
        echo '<fieldset data-role="fieldcontain" class="ui-wrapper-form">'.PHP_EOL;
        echo $this->formRow($this->registerProfileForm->get('name'), null, false).PHP_EOL;
        echo $this->formRow($this->registerProfileForm->get('gender'), null, false).PHP_EOL;
        echo $this->formRow($this->registerProfileForm->get('birthday'), null, false).PHP_EOL;
        echo $this->formRow($this->registerProfileForm->get('filename'), null, false).PHP_EOL;
        echo $this->formRow($this->registerProfileForm->get('country'), null, false).PHP_EOL;

        echo '</fieldset>'.PHP_EOL;
        echo '<fieldset data-role="controlgroup" data-type="horizontal">'.PHP_EOL;
                echo $this->formRow($this->registerProfileForm->get('submit'), null, false).PHP_EOL;
        echo '</fieldset>'.PHP_EOL;
    echo $this->form()->closeTag().PHP_EOL;
    ?>
    </div>
    <footer data-position="fixed" data-role="footer" class="ui-bar footer" data-theme="a">
        <h4>&copy; 2013  <a href="/"><?=$this->translate('Social Mobile', 'default')?></a> <?=$this->translate('powered by', 'default')?> <?=Zend\Version\Version::VERSION_SERVICE_ZEND;?> <?=Zend\Version\Version::VERSION;?> <?=$this->translate('All rights reserved.', 'default')?></h4>
    </footer>
</section
<?php $this->inlineScript()->appendScript(<<<EOT
$(document).ready(function(){
    $('input[name=birthday]').mask('9999-99-99', {placeholder: ""});
});
EOT
); ?>
<?php echo $this->socialPlugin('language'); // виджет выбора языка ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/mobile/jquery.mobile.datebox.css');?>
<?php $this->inlineScript()->appendFile($this->basePath().'/js/jquery.mousewheel.js', 'text/javascript');?>
<?php $this->inlineScript()->appendFile($this->basePath().'/js/datebox/jqm-datebox.core.js', 'text/javascript');?>
<?php $this->inlineScript()->appendFile($this->basePath().'/js/datebox/jqm-datebox.mode.datebox.js', 'text/javascript');?>
<?php $this->inlineScript()->appendFile($this->basePath().'/js/languages/jqm-datebox-'.$this->getLang('code').'.js', 'text/javascript');?>
<?php $this->inlineScript()->appendFile($this->basePath().'/js/mobile/tooltip.js', 'text/javascript');?>
<?php $this->inlineScript()->appendFile($this->basePath().'/js/form.storage.js', 'text/javascript');?>
<?php $this->inlineScript()->appendFile($this->basePath().'/js/jquery.maskedinput.js', 'text/javascript');?>
<?php echo $this->headLink();?>
<?php echo $this->InlineScript();?>
