<!-- Выбор месторасположения -->
<section data-role="page" data-theme="a">
    <?php echo $this->socialPlugin('header'); // заголовок jQuery Mobile ?>
    <div data-role="content" data-theme="a">
    <?php
    echo $this->formElementerrors($this->registerProfileForm, array('class' => "ui-error")).PHP_EOL; // сообщение об ошибке

    $this->registerProfileForm->setAttribute('action', $this->url($this->getRoute()->route['controller'],
                                                array('action' => $this->getRoute()->route['action'],  'lang'=>$this->getLang('code')),
                                                array('force_canonical'=>true)
                                )
    );
    echo $this->form()->openTag($this->registerProfileForm).PHP_EOL;
        echo $this->formRow($this->registerProfileForm->get('region'), null, false).PHP_EOL;
        echo '<fieldset data-role="controlgroup" data-type="horizontal">'.PHP_EOL;
                echo $this->formRow($this->registerProfileForm->get('back'), null, false).PHP_EOL;
                echo $this->formRow($this->registerProfileForm->get('submit'), null, false).PHP_EOL;
        echo '</fieldset>'.PHP_EOL;
    echo $this->form()->closeTag().PHP_EOL;
    ?>
    </div>
    <footer data-position="fixed" data-role="footer" class="ui-bar footer" data-theme="a">
        <h4>&copy; 2013  <a href="/"><?=$this->translate('Social Mobile', 'default')?></a> <?=$this->translate('powered by', 'default')?> <?=Zend\Version\Version::VERSION_SERVICE_ZEND;?> <?=Zend\Version\Version::VERSION;?> <?=$this->translate('All rights reserved.', 'default')?></h4>
    </footer>
</section>
<?php echo $this->socialPlugin('language'); // виджет выбора языка ?>
<?=$this->inlineScript()->appendFile($this->basePath().'/js/mobile/tooltip.js', 'text/javascript');?>
