<?php //Zend\Debug\Debug::dump($item); ?>
<div data-role="content" data-theme="a">
    <div class="ui-items-body">
        <div class="ui-hover-title">
            <?php echo $this->navigation('navigation')->breadcrumbs()->setTranslatorTextDomain('admin')->setMinDepth(0)->setSeparator(' ▶ ');
            echo $title; ?>
        </div>         
        <!-- Вывод мессенджера -->
            <?php echo $this->flashMessenger()->render('error', array('ui-error')); ?>
            <?php echo $this->flashMessenger()->render('success', array('ui-success')); ?>
        <!-- Вывод мессенджера -->	
        <nav data-role="navbar">
            <ul>
                <li><a href="javascript:;" class="ui-tab system" data-href="system"><?php echo $this->translate('Accesibility', 'admin');?></a>
                </li>
                <li><a href="javascript:;" class="ui-tab personal" data-href="personal"><?php echo $this->translate('Personal data', 'admin');?></a>
                </li>
                <li><a href="javascript:;" class="ui-tab settings" data-href="settings"><?php echo $this->translate('Settings', 'admin');?></a>
                </li>
                <li class="ui-tab-last"><a href="javascript:;" class="ui-tab location" data-href="location"><?php echo $this->translate('Location', 'admin');?></a>
                </li>                
            </ul>
        </nav>        
        
        <!-- Таблица -->
        <link href="<?php echo $this->basePath() . '/css/tables.css'; ?>" media="screen" rel="stylesheet" type="text/css">
        <form method="post">
            <input type="hidden" name="id" value="<?php echo $item->id; ?>">
            <fieldset id="system" class="inner-tabs boxshadow">
                <table class="ui-table" data-theme="a" border="1">
                    <tbody>
                        <tr class="ui-even">
                            <td width="30%">
                                <?php echo $this->translate('Login', 'admin'); ?>
                            </td>
                            <td>
                                <input type="text" name="login" data-clear-btn="true" data-mini="true" value="<?php echo $this->escapeHTML($item->login); ?>" placeholder="<?php echo $this->translate('Login must be required', 'admin'); ?>" required>
                            </td>
                        </tr>
                        <tr class="ui-odd">
                            <td>
                                <?php echo $this->translate('Password', 'admin'); ?>
                            </td>
                            <td>
                                <input type="password" name="password" data-clear-btn="true" data-mini="true" placeholder="<?php echo $this->translate('Leave this part blank if there is no need to change the password', 'admin'); ?>">                                
                            </td>
                        </tr>
                        <tr class="ui-even">
                            <td>
                                <?php echo $this->translate('Retype password', 'admin'); ?>
                            </td>
                            <td>
                                <input type="password" name="repassword" data-clear-btn="true" data-mini="true" value="">
                            </td>
                        </tr>                        
                        <tr class="ui-odd">
                            <td>
                                <?php echo $this->translate('Group', 'admin'); ?>
                            </td>
                            <td>
                                <select name="role_id" data-mini="true">
                                    <?php foreach($roles as $role): ?>
                                    <option value="<?php echo $role['id']; ?>" <?php echo ($item->role_id == $role['id']) ? 'selected' : '' ?>><?php echo $role['name']; ?></option>
                                    <?php endforeach; ?>
                                </select>                                 
                            </td>
                        </tr>
                        <tr class="ui-even">
                            <td>
                                <?php echo $this->translate('Status', 'admin'); ?>
                            </td>
                            <td>
                                <select name="state" data-mini="true">
                                    <option value="0"<?php echo ($item->state == 0) ? ' selected' : '' ?>><?php echo $this->translate('disabled','admin');?></option>
                                    <option value="1"<?php echo ($item->state == 1) ? ' selected' : '' ?>><?php echo $this->translate('enabled','admin');?></option>
                                    <option value="2"<?php echo ($item->state == 2) ? ' selected' : '' ?>><?php echo $this->translate('banned','admin');?></option>
                                </select>                                   
                            </td>
                        </tr>                        
                    </tbody>                      
                </table>
            </fieldset>
            
            <fieldset id="personal" class="inner-tabs boxshadow">
                <table class="ui-table" data-theme="a" border="1">
                    <tbody>
                        <tr class="ui-even">
                            <td width="30%">
                                <?php echo $this->translate('Displayed name', 'admin'); ?>
                            </td>
                            <td>
                                <input type="text" name="name" data-clear-btn="true" data-mini="true" value="<?php echo $this->escapeHTML($item->name); ?>" placeholder="<?php echo $this->translate('Apparent user name must be required', 'admin'); ?>" required>                                
                            </td>
                        </tr>                        
                        <tr class="ui-odd">
                            <td>
                                <?php echo $this->translate('Email', 'admin'); ?>
                            </td>
                            <td>
                                <input type="email" name="email" data-clear-btn="true" data-mini="true" value="<?php echo $this->escapeHTML($item->email); ?>" placeholder="<?php echo $this->translate('Fill the contact email', 'admin'); ?>">      
                            </td>
                        </tr> 
                        <tr class="ui-even">
                            <td>
                                <?php echo $this->translate('Phone', 'admin'); ?>
                            </td>
                            <td>
                                <input type="text" name="phone" data-clear-btn="true" data-mini="true" value="<?php echo $this->escapeHTML($item->phone); ?>" placeholder="<?php echo $this->translate('Fill the contact phone number', 'admin'); ?>">      
                            </td>
                        </tr>                         
                        <tr class="ui-odd">
                            <td>
                                <?php echo $this->translate('Gender', 'admin'); ?>
                            </td>
                            <td>
                                <select name="gender" data-mini="true">
                                    <option value="1" <?php echo ($item->gender == 1) ? 'selected' : '' ?>><?php echo $this->translate('male', 'admin'); ?></option>
                                    <option value="2" <?php echo ($item->gender == 2) ? 'selected' : '' ?>><?php echo $this->translate('female', 'admin'); ?></option>                                    
                                </select>                                 
                            </td>
                        </tr>    
                        <tr class="ui-even">
                            <td>
                                <?php echo $this->translate('Birthday', 'admin'); ?>
                            </td>
                            <td>
<input type="text" name="birthday" id="birthday" data-mini="true" data-role="datebox" data-options="{&quot;mode&quot;: &quot;datebox&quot;, &quot;overrideDateFormat&quot; : &quot;%Y-%m-%d&quot;, &quot;useNewStyle&quot; : true, &quot;themeButton&quot; : &quot;a&quot;, &quot;themeInput&quot; : &quot;b&quot;, &quot;themeHeader&quot;: &quot;b&quot;}" value="<?php echo $this->escapeHTML($item->birthday); ?>">
                            </td>
                        </tr>  
                        <tr class="ui-odd">
                            <td>
                                <?php echo $this->translate('Height / Weight', 'admin'); ?>
                            </td>
                            <td>
                                <fieldset class="ui-grid-a">
                                    <div class="ui-block-a">
                                        <input type="text" pattern="^\d+$" name="length" data-mini="true" value="<?php echo $this->escapeHTML($item->length); ?>" maxlength="3" size="3">
                                    </div>
                                    <div class="ui-block-b">
                                        <input type="text" pattern="^\d+$" name="weight" data-clear-btn="true" data-mini="true" value="<?php echo $this->escapeHTML($item->weight); ?>" maxlength="3" size="3" >
                                    </div>
                                </fieldset>                                
                            </td>
                        </tr>                           
                        <tr class="ui-even">
                            <td>
                                <?php echo $this->translate('Interests', 'admin'); ?>
                            </td>
                            <td>
                                <textarea name="interests">
                                    <?php echo $this->escapeHTML($item->interests); ?>
                                </textarea>
                            </td>
                        </tr>    
                        <tr class="ui-odd">
                            <td>
                                <?php echo $this->translate('About', 'admin'); ?>
                            </td>
                            <td>
                                <textarea name="about">
                                    <?php echo $this->escapeHTML($item->about); ?>
                                </textarea>
                            </td>
                        </tr>                         
                    </tbody>                      
                </table>
            </fieldset>  
            
            <fieldset id="settings" class="inner-tabs boxshadow">
                <table class="ui-table" data-theme="a" border="1">
                    <tbody>
                        <tr class="ui-even">
                            <td>
                                <?php echo $this->translate('Timezone', 'admin'); ?>
                            </td>
                            <td>
                                <select name="timezone" data-mini="true">
                                    <?php foreach(\SW\String\Format::getTimezones() as $k => $v): ?>
                                        <option value="<?php echo $k; ?>" <?php echo ($item->timezone == $k) ? 'selected' : '' ?>><?php echo $this->translate($v, 'timezones'); ?></option>
                                    <?php endforeach; ?>                                  
                                </select>                              
                            </td>
                        </tr>   
                        <tr class="ui-even">
                            <td>
                                <?php echo $this->translate('Alias', 'admin'); ?>
                            </td>
                            <td>
                                <input type="text" name="alias" data-clear-btn="true" data-mini="true" value="<?php echo $this->escapeHTML($item->alias); ?>">
                            </td>
                        </tr>  
                        <tr class="ui-odd">
                            <td>
                                <?php echo $this->translate('Rating', 'admin'); ?>
                            </td>
                            <td>
                                <input type="text" pattern="^\d+$" name="rating" data-clear-btn="true" data-mini="true" value="<?php echo $this->escapeHTML($item->rating); ?>">
                            </td>
                        </tr>                         
                    </tbody>                      
                </table>
            </fieldset>  
            
            <fieldset id="location" class="inner-tabs boxshadow">
                <table class="ui-table" data-theme="a" border="1">
                    <tbody>
                        <tr class="ui-odd">
                            <td>
                                <?php echo $this->translate('Country', 'admin'); ?>
                            </td>
                            <td>
                                <select name="country_id" data-mini="true" data-request="region" data-response="country" class="json">
                                    <?php foreach($countries as $v): ?>
                                        <option value="<?php echo $v['id']; ?>" <?php echo ($item->country_id == $v['id']) ? 'selected' : '' ?>><?php echo $v['name']; ?></option>
                                    <?php endforeach; ?>                                  
                                </select> 
                            </td>
                        </tr> 
                        <tr class="ui-even">
                            <td>
                                <?php echo $this->translate('Region', 'admin'); ?>
                            </td>
                            <td>
                                <select name="region_id" data-request="city" data-response="region" data-mini="true" class="json">
                                    <?php foreach($regions as $v): ?>
                                        <option value="<?php echo $v['id']; ?>" <?php echo ($item->region_id == $v['id']) ? 'selected' : '' ?>><?php echo $v['name']; ?></option>
                                    <?php endforeach; ?>                                  
                                </select> 
                            </td>
                        </tr>
                        <tr class="ui-odd">
                            <td>
                                <?php echo $this->translate('City', 'admin'); ?>
                            </td>
                            <td>
                                <select name="city_id" data-mini="true" data-response="city">
                                    <?php foreach($cities as $v): ?>
                                        <option value="<?php echo $v['city_id']; ?>" <?php echo ($item->city_id == $v['city_id']) ? 'selected' : '' ?>><?php echo $v['name']; ?></option>
                                    <?php endforeach; ?>                                  
                                </select> 
                            </td>
                        </tr>                        
                    </tbody>                      
                </table>
            </fieldset>  
            <fieldset>
                <table class="ui-table" data-theme="a">
                    <tbody>
                        <tr>
                            <td>
                                <input type="submit" data-inline="true" data-icon="arrow-d" data-mini="true" value="<?php echo $this->translate('Save params', 'admin');?>">
                            </td>
                        </tr>
                    </tbody>                      
                </table>
            </fieldset>               
        </form>
        <!-- Таблица -->
    </div>
</div>
<?php
// Редирект на вкладку в случае ошибки формы
$redirect = $this->getRoute()->post('type');
if(isset($redirect))
{
    
    $this->inlineScript()->appendScript(<<<EOT
        $(document).ready(function(){
            $('a[data-href=".$redirect."]').click();
    });
EOT
    );
}
?>
<script type="text/javascript">
$(document).ready(function() {
    
    $('select.json').on('change', function(e) {
        e.preventDefault();
        
        /**
         * @var action params
         * @type array
         */
        var query   =   {}; 
        
        // formed request params 
        query['request']               =   $(this).data('request');
        query[$(this).attr('name')]    =   $(this).val();
        
        // send request
        Locations.request('/locations/json', query, 'POST');
    });
    
    
    $('input[name=birthday]').mask('9999-99-99', {placeholder: ""});
});    
</script>

<?php $this->headLink()->appendStylesheet($this->basePath().'/css/mobile/jquery.mobile.datebox.css');?>
<?php $this->inlineScript()->appendFile($this->basePath().'/js/jquery.mousewheel.js', 'text/javascript');?>
<?php $this->inlineScript()->appendFile($this->basePath().'/js/datebox/jqm-datebox.core.js', 'text/javascript');?>
<?php $this->inlineScript()->appendFile($this->basePath().'/js/datebox/jqm-datebox.mode.datebox.js', 'text/javascript');?>
<?php $this->inlineScript()->appendFile($this->basePath().'/js/languages/jqm-datebox-'.$this->getLang('code').'.js', 'text/javascript');?>
<?php $this->inlineScript()->appendFile($this->basePath().'/js/jquery.maskedinput.js', 'text/javascript');?>
<?php $this->inlineScript()->appendFile($this->basePath().'/js/locations.js', 'text/javascript');?>
<?php echo $this->headLink();?>
<?php echo $this->InlineScript();?>
