    <div data-role="content" data-theme="a">
        <div class="ui-items-body">
            <div class="ui-hover-title">
                <?php echo $this->navigation('navigation')->breadcrumbs()->setTranslatorTextDomain('admin')->setMinDepth(0)->setSeparator(' ▶ '); ?>
            </div>           
            <link href="<?php echo $this->basePath().'/css/tables.css'; ?>" media="screen" rel="stylesheet" type="text/css">
            <!-- Фильтры -->
            <br>
            <form action="" method="get" data-ajax="false" id="filter" class="ui-form-topover">
                <table class="ui-table" data-theme="a">
                    <thead>
                        <tr>
                            <th class="ui-center">
                                <input type="text" pattern="^\d+$" name="id" autocomplete="off" data-mini="true" maxlength="9" size="9" placeholder="<?php echo $this->translate('IDentifier' , 'admin');?>" value="<?php echo $this->escapeHTML($this->getRoute()->get('id')); ?>">
                            </th>                            
                            <th class="ui-center">
                                <input type="text" name="login" autocomplete="off" data-mini="true" maxlength="35" size="21" placeholder="<?php echo $this->translate('Please typing login here...' , 'admin');?>" value="<?php echo $this->escapeHTML($this->getRoute()->get('login')); ?>">
                                <ul data-suggestion="login" data-role="listview" data-inset="true" class="ui-hide ui-autocomplete"></ul>
                            </th>
                            <th class="ui-center">
                                <input type="text" name="name" autocomplete="off" data-mini="true" maxlength="35" size="21" placeholder="<?php echo $this->translate('Please typing name...' , 'admin');?>" value="<?php echo $this->escapeHTML($this->getRoute()->get('name')); ?>">
                                <ul data-suggestion="name" data-role="listview" data-inset="true" class="ui-hide ui-autocomplete"></ul>
                            </th>                                
                            <th class="ui-center">
                                <fieldset data-role="controlgroup" data-type="horizontal">
                                    <select name="state" id="state" data-mini="true">
                                        <option value="" selected="selected"><?php echo $this->translate('Select status' , 'admin');?></option>
                                        <option value="0"><?php echo $this->translate('disabled' , 'admin');?></option>
                                        <option value="1"><?php echo $this->translate('enabled' , 'admin');?></option>
                                        <option value="2"><?php echo $this->translate('banned' , 'admin');?></option>
                                    </select>                                    
                                    <select name="role_id" id="role_id" data-mini="true">
                                        <option value="" selected="selected"><?php echo $this->translate('Select role' , 'admin');?></option>
                                        <?php foreach($roles as $role): ?>
                                        <option value="<?php echo $role['id']; ?>"><?php echo $role['name']; ?></option>
                                        <?php endforeach; ?>
                                    </select>
                                    <select name="order" id="order" data-mini="true">
                                        <option value="" selected="selected"><?php echo $this->translate('Sorting by...' , 'admin');?></option>
                                        <option value="id"><?php echo $this->translate('ID' , 'admin');?></option>
                                        <option value="login"><?php echo $this->translate('Login' , 'admin');?></option>
                                        <option value="name"><?php echo $this->translate('Name' , 'admin');?></option>
                                        <option value="birthday"><?php echo $this->translate('Birthday' , 'admin');?></option>
                                        <option value="role_id"><?php echo $this->translate('Role' , 'admin');?></option>
                                        <option value="rating"><?php echo $this->translate('Rating' , 'admin');?></option>
                                        <option value="date_registration"><?php echo $this->translate('Register date' , 'admin');?></option>
                                        <option value="date_lastvisit"><?php echo $this->translate('Last visit date' , 'admin');?></option>
                                        <option value="time_online"><?php echo $this->translate('Most visited' , 'admin');?></option>
                                    </select>                            
                                    <input type="submit" data-inline="true" data-icon="search" data-mini="true" value="<?php echo $this->translate('Search' , 'admin');?>"> 
                                    <input type="reset" onclick="location.href='<?php echo $this->url('users'); ?>';" data-inline="true" data-icon="refresh" data-mini="true" value="<?php echo $this->translate('Reset' , 'admin');?>">                                                        
                                </fieldset>                            
                            </th>                                
                        </tr>
                    </thead>
                </table>
            </form>
            <script type="text/javascript">
                function put(event)
                {
                    // relation attribute
                    var rel     =   event.getAttribute('rel');
                    // insert value from list
                    $('input[name='+rel+']').val(event.text);
                    // close list
                    $('[data-suggestion='+rel+']').html('').addClass('ui-hide').listview('refresh');
                }
                    
                $('#page').on('pageshow', function(e) 
                {
                    /**
                     * @var list
                     * @type object
                     */
                    var list    =   {
                        fields      :   $('input[name=login], input[name=name]'),
                        result      :   '',
                        suggestion  :   '',
                    };

                    // action push key button
                    list.fields.on("input", function(e) {
                        
                        var query   =   {
                            fields  :  {}
                        }  
                        
                        // определю с каким списком работаю
                        var name = $(this).attr('name');
                        list.suggestion =   $('[data-suggestion='+name+']');
                        list.suggestion.listview('refresh');                        

                        if($(this).val().length < 3)
                        {
                            // очищаю и обновляю список с результатами
                            list.suggestion.html('').addClass('ui-hide').listview('refresh');
                        }
                        else
                        {
                            // от трех символов и >
                            query.fields[name] = $(this).val();

                            $.post('/admin/users/json', query.fields, function(res) 
                            {

                                if(res.length > 0)
                                {
                                    // если что либо найдено, добавляю в список
                                    res.forEach(function(entry) 
                                    {
                                        list.result += '<li><a href="#" rel="'+name+'" onclick="put(this); return false;">'+entry[name]+'</a></li>';
                                    });
x                                    list.suggestion.html(list.result).removeClass('ui-hide');
                                }
                                else list.suggestion.html('').addClass('ui-hide');

                            },"json").complete(function() 
                            { 
                                list.result = ''; // очистка списка
                                list.suggestion.listview('refresh');
                            });                           
                        }
                    }).focusout(function(){
                        list.result = '';       // очистка списка
                        //list.suggestion.html('').addClass('ui-hide').listview('refresh');
                    });
                });
            </script>
            <br>
            <!-- Фильтры -->
            
            <!-- Вывод мессенджера -->
                <?php echo $this->flashMessenger()->render('error', array('ui-error')); ?>
                <?php echo $this->flashMessenger()->render('success', array('ui-success')); ?>
            <!-- Вывод мессенджера -->
            
            <?php if(sizeof($items) > 0): ?>
	    <!-- Таблица пользователей -->
	    <form method="post">
                <table class="ui-table" data-theme="a" border="1">
                    <thead class="ui-table-hover">
                        <tr>
                            <th>
                                <label for="all"><?php echo $this->translate('All' , 'admin');?></label>
                                <input type="checkbox" name="all" id="all" data-mini="true" value="1">
                            </th>
                            <th>
                                <span><?php echo $this->translate('User' , 'admin');?></span>
                            </th>                                
                            <th>
                                <span><?php echo $this->translate('Photo' , 'admin');?></span>
                            </th>                                
                             <th>
                                <span><?php echo $this->translate('Location' , 'admin');?></span>
                            </th>                                
                            <th>
                                <span><?php echo $this->translate('Group' , 'admin');?></span>
                            </th>
                            <th>
                                <span><?php echo $this->translate('Register date' , 'admin');?></span>
                            </th>                            
                            <th>
                                <span><?php echo $this->translate('Status' , 'admin');?></span>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $i = 0; foreach($items as $item):?>
			<?php $class	=   ($i++ % 2 == 0) ? 'ui-even' : 'ui-odd'; ?>
			<tr class="<?php echo $class?>">
                            <td class="ui-center">
                                <fieldset data-role="controlgroup" data-type="horizontal">
                                    <label for="select-<?php echo $item->id?>"><?php echo $item->id?></label>
                                    <input title="<?php echo $this->translate('Check this' , 'admin');?>" type="checkbox" name="select[]" id="select-<?php echo $item->id?>" data-mini="true" value="<?php echo $item->id?>">
                                    <a data-role="button" title="<?php echo $this->translate('edit' , 'admin');?>" data-mini="true" href="/admin/<?php echo $this->getLang('code');?>/users/edit/<?php echo $item->id?>"><?php echo $this->translate('edit' , 'admin');?></a>
                                </fieldset>
                            </td>
                            <td class="ui-center ui-left">
                                <a href="/admin/<?php echo $this->getLang('code');?>/users/view/<?php echo $item->id?>">
                                    <span class="<?php if($item->gender == 2):?>ui-f<?php else:?>ui-m<?php endif;?>"></span> <?php echo $item->name?>
                                </a> 
                            </td>
                            <td class="ui-center">
                               	<?php if($item->photo):?>
				    <img class="ui-img-list" src="/files/images/thumb/<?php echo $item->id;?>/<?php echo $item->photo;?>" />
				<?php else:?>
				    <img class="ui-img-list" src="/images/mobile/<?php if($item->gender == 2):?>female.png<?php else:?>male.png<?php endif;?>" />
				<?php endif;?>
                            </td>
                            <td class="ui-center ui-left">
                                <span class="ui-location-string">
                                    <img class="ui-small-flag" src="/images/flags/small/<?php echo strtolower($item->country_code);?>.png" alt="" /> <?php echo $item->country;?> » <?php echo $item->region;?>, <?php echo $item->city;?>
                                </span>
                            </td>
                            <td class="ui-center">
                                <span data-role="button" data-mini="true" disabled="disabled" class="ui-status-container <?php echo $item->role_class;?>">
                                    <?php echo $item->role;?>
                                </span>
                            </td>
                            <td class="ui-center">
                                <?php
                                $this->plugin("dateFormat")->setTimezone($item->timezone)->setLocale($this->getLang('code').'_'.  strtoupper($this->getLang('code')));
                                echo $this->dateFormat(
                                        new DateTime($item->date_registration),
                                        IntlDateFormatter::MEDIUM,      // date
                                        IntlDateFormatter::MEDIUM       // time
                                    );
                                ?>
                            </td>               
                            <td class="ui-center">
                                <?php switch($item->state): 
                                    case 0: ?>
                                    <span data-role="button" data-mini="true" disabled="disabled" class="ui-status-container ui-red">
                                        <?php echo $this->translate('disabled' , 'admin');?>
                                    </span>
                                    <?php break; ?>
                                    <?php case 1: ?>
                                    <span data-role="button" data-mini="true" disabled="disabled" class="ui-status-container ui-green">
                                        <?php echo $this->translate('enabled' , 'admin');?>
                                    </span>                                
                                    <?php break; ?>
                                    <?php case 2: ?>
                                    <span data-role="button" data-mini="true" disabled="disabled" class="ui-status-container ui-yellow">
                                        <?php echo $this->translate('banned' , 'admin');?>
                                    </span>                                
                                    <?php break; ?>                                
                                <?php endswitch; ?>
                            </td>
			</tr>
			<?php endforeach;?>
                        <tr class="tfoot">
                            <td colspan="7">
                                <!-- Навигация -->
                                <?php echo ($items->getCurrentItemCount() > 0) ? $this->paginationControl($items, 'sliding', 'plugins/admin-pager') : '' ?>
                                <!-- Навигация -->
                                <!-- Панель управления CRUD -->
                                <fieldset data-role="controlgroup" data-type="horizontal"> 
                                    <legend><?php echo $this->translate('What to do with markup ?', 'admin');?></legend>
                                    <label>
                                        
                                        <select name="roleAction" id="roleAction" data-mini="true">
                                            <option value=""><?php echo $this->translate('Group', 'admin');?></option>
                                            <?php foreach($roles as $role): ?>
                                            <option value="<?php echo $role['id']; ?>"><?php echo $role['name']; ?></option>
                                            <?php endforeach; ?>
                                        </select>                                         
                                    </label>  
                                    <label>
                                        <?php echo $this->translate('Ban', 'admin');?><input id="banAction" type="radio" name="action" data-inline="true" data-mini="true" value="banAction">
                                    </label>                             
                                    <label>
                                        <?php echo $this->translate('Unban', 'admin');?><input id="enableAction" type="radio" name="action" data-inline="true" data-mini="true" value="enableAction">
                                    </label> 
                                    <label>
                                        <?php echo $this->translate('Enable', 'admin');?><input id="enableAction" type="radio" name="action" data-inline="true" data-mini="true" value="enableAction">
                                    </label>
                                    <label>
                                        <?php echo $this->translate('Disable', 'admin');?><input id="disableAction" type="radio" name="action" data-inline="true" data-mini="true" value="disableAction">
                                    </label>
                                    <label>
                                        <?php echo $this->translate('Delete', 'admin');?><input id="deleteAction" type="radio" name="action" data-inline="true" data-mini="true" value="deleteAction">
                                    </label>                                    
                                    <input type="submit" data-inline="true" data-icon="arrow-d" data-mini="true" value="<?php echo $this->translate('Do it!', 'admin');?>">
                                </fieldset>
                                <!-- Панель управления CRUD -->                                     
                            </td>
                        </tr>
                    </tbody>                      
                </table>
	    </form>
	    <!-- Таблица пользователей -->
            <?php endif; ?>
        </div>
    </div>