    <div data-role="content" data-theme="a">
        <div class="ui-items-body">
            <div class="ui-hover-title">
                <?php echo $this->navigation('navigation')->breadcrumbs()->setTranslatorTextDomain('admin')->setMinDepth(0)->setSeparator(' ▶ '); echo $title; ?>
            </div>           
            <!-- Вывод мессенджера -->
                <?php echo $this->flashMessenger()->render('error', array('ui-error')); ?>
                <?php echo $this->flashMessenger()->render('success', array('ui-success')); ?>
            <!-- Вывод мессенджера -->
        </div>
    </div>