<?php $this->socialPlugin('statistics');// плагин сбора статистики ?>
<?=$this->doctype();?>
<html lang="<?=$this->lang;?>" xmlns:og="http://ogp.me/ns#">
    <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb#">
        <?php
            // Устанавливаю правильный заголовок страницы
            if($this->serverUrl().'/' != $this->serverUrl(true)) 
                $this->headTitle($this->translate('Social Mobile', 'default'), "prepend")->setSeparator(' | ')->setAutoEscape(false);
            echo $this->headTitle();
        ?>
        <?=$this->headMeta()
                // META информация
                ->setCharset('UTF-8')
                ->appendName('keywords',        '')
                ->appendName('description',     '')
                ->appendName('viewport',        'width=device-width, initial-scale=1, maximum-scale=1')
                ->appendName('generator',       'Zend Framework '.Zend\Version\Version::VERSION)
                ->appendName('author',          'Stanislav WEB')

                // Open Graph

                ->setProperty('og:title',        strip_tags($this->headTitle()))
                ->setProperty('og:type',         'article')
                ->setProperty('og:url',          $this->serverUrl(true))
                ->setProperty('og:image',        $this->serverUrl().'/images/mobile/logo.png')
                ->setProperty('og:site_name',    $this->translate('Social Mobile', 'default'))
                ->setProperty('og:description',  '');
        ?>
        <?=$this
                ->headLink(array('rel'=>'shortcut icon', 'href'=>$this->basePath().'/images/favicon.ico'))
                ->appendStylesheet($this->basePath().'/css/mobile/mobile.css')
        ?>
	
        <?=$this->headScript()
                ->appendFile($this->basePath().'/js/jquery.min.js')
                ->appendFile($this->basePath().'/js/languages/'.$this->lang.'.js')
                ->appendFile($this->basePath().'/js/mobile/init.js')
                ->appendFile($this->basePath().'/js/mobile/jquery.mobile.min.js');
        ?>
    </head>
    <body>    
        <?=$this->content;?>
    </body>
</html>