<?php
/**
 * Перевод почтовых шаблонов
 * Language: Русский язык
 * Domain: mails
 * Author: Stanislav WEB
 */

return array(

    // Восстановление доступа
    "We are in VK.com"  =>  "Мы Вконтакте",
    "Password recovery on \"%s\""   =>  "Восстановление пароля на сайте \"%s\"",
    "Best regadrs, site Administration"    =>  "С уважением к в Вам, Администрация сайта",
    "On all issues of cooperation, promotion, problems and complaints please email" =>  "По всем вопросам сотрудничества, рекламе, проблемам и жалобам обращайтесь на email",
);
