<?php 
// setup current time formats
$this->plugin("dateFormat")->setTimezone($user->timezone)->setLocale($this->getLang('code').'_'.  strtoupper($this->getLang('code')));
?>   
<section data-role="page" data-theme="a">
    <?php echo $this->socialPlugin('header', $user); // заголовок ?>
    <!-- Меню -->
    <div data-role="content" data-theme="a">
        <div class="ui-user-body">
            <div class="ui-hover-title">
                <?php echo $this->socialPlugin('menu', 'user-topnav-menu', $user); // верхнее меню навигации пользователя ?>
            </div>
            <div class="ui-grid-b">
                <div class="ui-block-a">
                    <!-- Аватар -->
                    <div class="ui-avatar-wrap">
                        <?php if($user->photo):?>
                        <img class="ui-img-list" src="/files/images/profile/<?php echo $user->id;?>/<?php echo $user->photo;?>" />
                        <?php else: ?>
                            <?php if($user->gender == 1):?>
                                <img class="ui-img-list" src="/images/mobile/user/no_avatar_m.png" />
                            <?php else:?>
                                <img class="ui-img-list" src="/images/mobile/user/no_avatar_f.png" />
                            <?php endif;?>
                        <?php endif;?>
                    </div>
                     <?php  $this->socialPlugin('breadcrumbs'); // хлебные  ?>
                    <!-- Аватар -->
                </div>
                <div class="ui-block-b">
                    <!-- Инфо -->
                        <?php echo$this->translate('Register date', 'default')?> : <?php echo $this->dateFormat(
                                        new DateTime($user->date_registration),
                                        IntlDateFormatter::MEDIUM,      // date
                                        IntlDateFormatter::MEDIUM       // time
                                    );?><br>
                        <?php echo$this->translate('My last visit', 'default')?> : <?php echo $this->dateFormat(
                                        new DateTime($user->date_lastvisit),
                                        IntlDateFormatter::MEDIUM,      // date
                                        IntlDateFormatter::MEDIUM       // time
                                    );?><br>
                        <?php if($user->time_online > 60):?><?php echo $this->translate('I stayed online', 'default')?> : <?php echo $this->setString('secondsformat', $user->time_online);?><?php endif;?>
                    <!-- Инфо -->

                </div>                
                <div class="ui-block-c ui-whats-up">
                    <!-- Форма установки статуса -->
                    <?php  echo $this->setForm('PersonalForm', $user);?>
		    <script type="text/javascript">
$(document).ready(function(){
    //Open a WebSocket connection.
    var wsUri = "ws://zf.local:9000/websocket/open/chat";   
    websocket = new WebSocket(wsUri); 
    
    //Connected to server
    websocket.onopen = function(ev) {
        console.log('Connected to server ');
    }
    
    //Connection close
    websocket.onclose = function(ev) { 
        console.log('Disconnected');
    };
    
    //Message Receved
    websocket.onmessage = function(ev) { 
        console.log('Message '+ev.data);
    };
    
    //Error
    websocket.onerror = function(ev) { 
        console.log('Error '+ev.data);
    };
    
     //Send a Message
    $('#ssssss').click(function(e){ 
	e.preventDefault();
        var mymessage = 'Test'; 
        websocket.send('Hello every one! I go to do my best!');
	websocket.onmessage(e);
    });
});
		    </script>
		    <a href="#" id="ssssss" data-role="button">Send</a>
                    <!-- Форма установки статуса -->
                </div>
                <div class="ui-block-a">

                </div>
                <div class="ui-block-b">

                </div>
                <div class="ui-block-c">
                    
                </div>
            </div>
        </div>
    </div>
    <footer data-position="fixed" data-role="footer" class="ui-bar footer" data-theme="a">
        <h4>&copy; 2013  <a href="/"><?php echo$this->translate('Social Mobile', 'default')?></a> <?php echo $this->translate('powered by', 'default')?> <?php echo Zend\Version\Version::VERSION_SERVICE_ZEND;?> <?php echo Zend\Version\Version::VERSION;?> <?php echo $this->translate('All rights reserved.', 'default')?></h4>
    </footer>
</section>
<?php $this->inlineScript()->appendFile($this->basePath().'/js/socket.js', 'text/javascript');?>
<?php echo $this->InlineScript();?>
<?php echo $this->socialPlugin('language'); // виджет выбора языка ?>