<?php
/**
 * Перевод почтовых сообщений
 * Language: Українська мова
 * Domain: mails
 * Author: Stanislav WEB
 */

return array(

    // Восстановление доступа
    "We are in VK.com"  =>  "Ми Вконтакте.Ру",
    "Password recovery on \"%s\""   =>  "Відновлення пароля на сайті \"%s\"",
    "Best regadrs, site Administration"    =>  "З повагою до Вас, Адміністрація сайта",
    "On all issues of cooperation, promotion, problems and complaints please email" =>  "З усіх питань, щодо співпраці, реклами, проблемам і жалобам пишить на email",
);
