<?php
/**
 * Перевод сообщений об ошибках
 * Language: Русский язык
 * Domain: errors
 * Author: Stanislav WEB
 */

return array(
    'Action error! You can not send form without POST!' =>	'Произошла ошибка! Вы не можете отправить форму методом GET!',
    'Plugins not found'                                 =>	'Плагины не найдены',
    'Action not selected'                               =>	'Не выбрано действие',
    'Not selected items'                                =>	'Не выбраны плагины для обработки',
    'Action is not available'                           =>      'Действие не доступно',
    'Error while deleting'                              =>      'Ошибка при удалении',
    'Error while update status'                         =>      'Ошибка при обновлении статуса'
);
