<?php
/**
 * Перевод сообщений об ошибках
 * Language: Українська мова
 * Domain: errors
 * Author: Stanislav WEB
 */

return array(
    'Action error! You can not send form without POST!' =>	'Помилка! Ви не зможете відправити форму GET!',
    'Plugins not found'                                 =>	'Плагіни не знайдени',
    'Action not selected'                               =>	'Оберить дію',
    'Not selected items'                                =>	'Відмідьте плагіни для обробки',
    'Action is not available'                           =>      'Не зрозуміла дія',
    'Error while deleting'                              =>      'Помилка при видаленні',
    'Error while update status'                         =>      'Помилка при оновленні статусу'
);
