<?php
/**
 * Перевод основного модуля
 * Language: Русский язык
 * Domain: plugins (default)
 * Author: Stanislav WEB
 */

return array(
    
    'Title'         =>  'Название',
    'Description'   =>  'Описание',
    'Status'        =>  'Статус',
    'Read only'     =>  'Для чтения',
    'System code'   =>  'Системный код',
    'Filter: Please choise type'    =>  'Фильтр: пожалуйста выберите тип плагина',
    'Show'          =>  'Показать',
    'edit'          =>  'ред.',
    'Check this'    =>  'Отметить',
    'Register plugin'    =>  'Регистрировать плагин',
    'Enter the name of the plugin'  =>  'Введите название плагина',
    'Brief description of the plugin'   =>  'Краткое описание работы плагина',
    'The code in which a plug can be identified'    =>  'Код, по которому можно идентифицировать плагин',
    'Typing your plugin'    =>  'Типизация вашего плагина',
    'Set activity status'   =>  'Установите статус активности',
    'Set readonly mode (read - mosly system plugins)'    =>  'Режим "для чтения" - в основном системные плагины',
    
    // Флэш стена
    
    'Live Wall'                 =>  'Живая стена',
    'There are nobody wrote'    =>  'Сдесь еще никто не писал :(',
    
    /* Информер онлайн */
    
    'Online is %s %s'       =>  'Сейчас на сайте %s %s',
    
    
    /* Месяца */
    
    'of January'    =>  'января',
    'of February'   =>  'февраля',
    'of Marth'      =>  'марта',
    'of April'      =>  'апреля',
    'of May'        =>  'мая',
    'of June'       =>  'июня',
    'of July'       =>  'июля',
    'of August'     =>  'августа',
    'of September'  =>  'сентября',
    'of October'    =>  'октября',
    'of November'   =>  'ноября',
    'of December'   =>  'декабря',
    
    
    'first'	=> 'первая',
    'prev'	=> 'пред',
    'next'	=> 'след',
    'last'	=> 'последняя',    
);