<?php
/**
 * Перевод основного модуля
 * Language: Русский язык
 * Domain: plugins (default)
 * Author: Stanislav WEB
 */

return array(
    
    // Флэш стена
    
    'Live Wall'    =>  'Живая стена',
    'There are nobody wrote'    =>  'Сдесь еще никто не писал :(',
    
    /* Информер онлайн */
    
    'Online is %s %s'       =>  'Сейчас на сайте %s %s',
    
    
    /* Месяца */
    
    'of January'    =>  'января',
    'of February'   =>  'февраля',
    'of Marth'      =>  'марта',
    'of April'      =>  'апреля',
    'of May'        =>  'мая',
    'of June'       =>  'июня',
    'of July'       =>  'июля',
    'of August'     =>  'августа',
    'of September'  =>  'сентября',
    'of October'    =>  'октября',
    'of November'   =>  'ноября',
    'of December'   =>  'декабря',
    
    
    'first'	=> 'первая',
    'prev'	=> 'пред',
    'next'	=> 'след',
    'last'	=> 'последняя',    
);