<?php
/**
 * Перевод основного модуля
 * Language: Українська мова
 * Domain: plugins (default)
 * Author: Stanislav WEB
 */

return array(
    
    'Title'         =>  'Назва',
    'Description'   =>  'Опис',
    'Status'        =>  'Статус',
    'Read only'     =>  'Для читання',
    'System code'   =>  'Системний код',
    'Filter: Please choise type'    =>  'Фільтр: будь ласка, виберіть тип плагіна',
    'Show'          =>  'Показати',
    'edit'          =>  'ред.',
    'Check this'    =>  'Відмітити',

    // Флэш стена
    
    'Live Wall'    =>  'Жива стіна',
    'There are nobody wrote'    =>  'Тут ще нікого не було :(',
    /* Информер онлайн */
    
    'Online is %s %s'       =>  'Зараз на сайті %s %s',
    
    /* Місяці */
    
    'of January'    =>  'січня',
    'of February'   =>  'лютого',
    'of Marth'      =>  'березня',
    'of April'      =>  'квітня',
    'of May'        =>  'травня',
    'of June'       =>  'червня',
    'of July'       =>  'липня',
    'of August'     =>  'серпня',
    'of September'  =>  'вересня',
    'of October'    =>  'жовтня',
    'of November'   =>  'листопада',
    'of December'   =>  'грудня',
    
    'Jan'       =>  'янв',
    'Feb'       =>  'фев',
    'Mar'       =>  'мар',
    'Apr'       =>  'апр',
    'May'       =>  'мая',
    'Jun'       =>  'июн',
    'Jul'       =>  'июл',
    'Aug'       =>  'авг',
    'Sep'       =>  'сен',
    'Oct'       =>  'окт',
    'Nov'       =>  'ноя',
    'Dec'       =>  'дек',
    
    
    'first'	=> 'перша',
    'prev'	=> 'попер',
    'next'	=> 'наст',
    'last'	=> 'остання',
);