<?php $format = new \SW\String\Format; ?>   
<?php $dateReg  = $format->getFormatTime($user->date_registration, $user->timezone); // формат даты регистрации?>
<?php $dateLast = $format->getFormatTime($user->date_lastvisit, $user->timezone);    // формат даты последнего визита ?>
<section data-role="page" data-theme="a">
    <?php echo $this->socialPlugin('header'); // заголовок jQuery Mobile ?>
    <div data-role="content" data-theme="a">
        <div class="ui-user-body">
            <div class="ui-hover-title">
                <?php echo $this->socialPlugin('menu', 'user-topnav-menu', $user); // верхнее меню навигации пользователя ?>
            </div>
            <div class="ui-grid-b">
                <div class="ui-block-a">
                    <!-- Аватар -->
                    <div class="ui-avatar-wrap">
                        <?php if($user->photo):?>
                        <img class="ui-img-list" src="/files/images/profile/<?=$user->id;?>/<?=$user->photo;?>" />
                        <?php else: ?>
                            <?php if($user->gender == 1):?>
                                <img class="ui-img-list" src="/images/mobile/user/no_avatar_m.png" />
                            <?php else:?>
                                <img class="ui-img-list" src="/images/mobile/user/no_avatar_f.png" />
                            <?php endif;?>
                        <?php endif;?>
                    </div>
                     <?php  $this->socialPlugin('breadcrumbs'); // хлебные  ?>

                    <!-- Аватар -->
                </div>
                <div class="ui-block-b">
                    <!-- Инфо -->
                        <?=$this->translate('Register date', 'default')?> : <?php echo $dateReg['d'].' '.$this->translate($dateReg['m'], 'plugins').' '.$dateReg['y'];?><br>
                        <?=$this->translate('My last visit', 'default')?> : <?php echo $dateLast['d'].' '.$this->translate($dateLast['m'], 'plugins').' '.$dateLast['y'].' '.$dateLast['h'].':'.$dateLast['i'];?><br>
                        <?php if($user->time_online > 60):?><?=$this->translate('I stayed online', 'default')?> : <?php echo $this->setString('secondsformat', $user->time_online);?><?php endif;?>
                    <!-- Инфо -->
                </div>                
                <div class="ui-block-c ui-whats-up">

                </div>
                <div class="ui-block-a">
                    
                </div>
                <div class="ui-block-b">

                </div>
                <div class="ui-block-c">
                    
                </div>
            </div>
        </div>
    </div>
    <footer data-position="fixed" data-role="footer" class="ui-bar footer" data-theme="a">
        <h4>&copy; 2013  <a href="/"><?=$this->translate('Social Mobile', 'default')?></a> <?=$this->translate('powered by', 'default')?> <?=Zend\Version\Version::VERSION_SERVICE_ZEND;?> <?=Zend\Version\Version::VERSION;?> <?=$this->translate('All rights reserved.', 'default')?></h4>
    </footer>
</section>
<?php echo $this->socialPlugin('language'); // виджет выбора языка ?>