        <?php
        $this->form->setAttribute('action', $this->url(
                                    'social',
                                    array(
                                        'action'    =>  'search'
                                    )
                                )
        );
        echo $this->form()->openTag($this->form);
            echo '<fieldset data-role="fieldcontain">';
                echo $this->formRow($this->form->get('search'));
            echo '</fieldset>';
            echo '<fieldset data-role="controlgroup" data-type="horizontal">';
                echo $this->formRow($this->form->get('gender'));
                echo $this->formRow($this->form->get('online'));
                echo $this->formRow($this->form->get('photo'));
                echo $this->formRow($this->form->get('submit'));
            echo '</fieldset>';
        echo $this->form()->closeTag();
        ?>