<div data-role="content" data-theme="a">
    <div class="ui-admin-body">
        <div class="ui-hover-title">
            <?php echo $this->navigation('navigation')->breadcrumbs()->setTranslatorTextDomain('admin')->setMinDepth(0)->setSeparator(' ▶ '); ?> 
        </div>           
        <!-- Вывод мессенджера -->
        <?php echo $this->flashMessenger()->render('error', array('ui-error')); ?>
        <?php echo $this->flashMessenger()->render('success', array('ui-success')); ?>
        <!-- Вывод мессенджера -->
        <!-- Меню выбора провайдера -->
        <div class="ui-grid-a">
            <div class="ui-block-a">
                <ul data-role="listview" data-inset="true" class="ui-main-menu">
                    <?php foreach ($providers as $provider => $params): ?>
                        <li class="ui-li-has-thumb" data-icon="false">
                            <a data-role="button" class="ui-admin-item" href="/admin/distributions/view/<?php echo $provider; ?>" title="<?php echo $params['description']; ?>">
                                <img class="ui-img-list" src="<?php echo $params['icon']; ?>">
                                <div class="ui-menu-description">
                                    <span><?php echo $provider; ?></span>
                                    <span><?php echo $params['description']; ?></span>
                                </div>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>                    
            </div>
            <div class="ui-block-b">

            </div>                
        </div>            
        <!-- Меню выбора провайдера -->
    </div>
</div>