<section data-role="page" data-theme="a">
    <header data-role="header" data-theme="a" data-position="fixed" class="ui-admin-header">
        <div class="ui-grid-a">
            <div class="ui-block-a">
                <a href="#Language" title="<?php echo $this->translate('Choose a language' , 'default');?>" class="ui-hover-btn ui-admin-nav-btn" data-role="button" data-rel="dialog"><img src="/images/flags/small/<?php echo $this->getLang('code');?>.png" alt="<?php echo $this->getLang('code');?>" /></a>
                <a href="#" id="login" title="Администратор" class="ui-hover-btn ui-admin-nav-btn" data-role="button" data-rel="dialog"><img src="/images/admin/admin.gif" alt="Администратор" />&nbsp;&nbsp;<span><?php echo $this->user->name?></span></a>                
            </div>
            <div class="ui-block-b">
                <h1 class="ui-admin-logo">
                    <a href="<?php echo $this->url('social' , ['lang' => $this->getLang('code')] , ['force_canonical' => true]);?>"><img src="/images/mobile/logo.png" alt="Logo"></a>
                </h1>              
            </div>
            <div class="ui-block-c" align="right">
                <a href="#" class="ui-hover-btn ui-admin-nav-btn" data-role="button" onclick="return false;" id="clock" data-rel="dialog"></a>
                <a href="<?php echo $this->url('admin' , ['lang' => $this->getLang('code') ,'action' => 'logout'] , ['force_canonical' => true]);?>" title="<?php echo $this->translate('Logout' , 'admin');?>" class="ui-hover-btn ui-admin-nav-btn" data-transition="pop" data-role="button"><img src="/images/admin/mini_logout.png" alt="<?php echo $this->translate('Logout' , 'admin')?>" /></a>                
            </div>
        </div>
    </header>
    <div data-role="content" data-theme="a">
        <div class="ui-admin-body">
            <div class="ui-hover-title">
                <?php echo $title; ?>
            </div>           
            <!-- Вывод мессенджера -->
                <?php echo $this->flashMessenger()->render('error', array('ui-error')); ?>
                <?php echo $this->flashMessenger()->render('success', array('ui-success')); ?>
            <!-- Вывод мессенджера -->
	    <!-- Меню выбора провайдера -->
            <div class="ui-grid-a">
                <div class="ui-block-a">
                    <ul data-role="listview" data-inset="true" class="ui-main-menu">
                        <?php foreach($providers as $provider => $params): ?>
                            <li class="ui-li-has-thumb" data-icon="false">
                                <a data-role="button" class="ui-admin-item" href="/admin/distributions/view/<?php echo $provider;?>" title="<?php echo $params['description'];?>">
                                    <img class="ui-img-list" src="<?php echo $params['icon'];?>">
                                    <div class="ui-menu-description">
                                        <span><?php echo $provider;?></span>
                                        <span><?php echo $params['description'];?></span>
                                    </div>
                                </a>
                            </li>
                        <?php endforeach;?>
                    </ul>                    
                </div>
                <div class="ui-block-b">
                    
                </div>                
            </div>            
	    <!-- Меню выбора провайдера -->
        </div>
    </div>
    <footer data-position="fixed" data-role="footer" class="ui-bar footer" data-theme="a">
        <h4>&copy; 2013  <a href="/"><?php echo $this->translate('Social Mobile' , 'default')?></a> <?php echo $this->translate('powered by' , 'default')?> <?php echo Zend\Version\Version::VERSION_SERVICE_ZEND;?> <?php echo Zend\Version\Version::VERSION;?> <?php echo $this->translate('All rights reserved.' , 'default')?></h4>
    </footer>
</section>
<?php echo $this->socialPlugin('language'); // виджет выбора языка ?>
